<?php

require '../vendor/autoload.php';

$smarty = new Smarty;
$smarty->left_delimiter = "<%";
$smarty->right_delimiter = "%>";

$smarty->setCaching(Smarty::CACHING_OFF);

$home = array (
  "id"=>"1",
  "haschildren"=>"1",
  "reid"=>"0",
  "link"=>"/",
  "name"=>"首页",
  "children"=>array (
    array (
      "id"=>"11",
      "haschildren"=>"1",
      "reid"=>"1",
      "link"=>"/channel/special.html",
      "name"=>"专题报道",
      "children"=>array (
        array (
          "id"=>"80",
          "haschildren"=>"0",
          "reid"=>"11",
          "link"=>"/channel/datanews.html",
          "name"=>"数据新闻",
          "children"=>array(),
          "code"=>"datanews",
          "type"=>"channel",
        ),
        array (
          "id"=>"81",
          "haschildren"=>"0",
          "reid"=>"11",
          "link"=>"/tag/2015%E8%BE%BE%E6%B2%83%E6%96%AF",
          "name"=>"2015达沃斯",
          "children"=>array (),
          "code"=>"2015davos",
          "type"=>"link",
        ),
        array (
          "id"=>"82",
          "haschildren"=>"0",
          "reid"=>"11",
          "link"=>"/tag/与FT共进午餐",
          "name"=>"与FT共进午餐",
          "children"=>array (),
          "code"=>"lunch",
          "type"=>"link",
        ),
      ),
      "code"=>"special",
      "type"=>"channel",
    ),
    array (
      "id"=>"12",
      "haschildren"=>"1",
      "reid"=>"1",
      "link"=>"/channel/weekly.html",
      "name"=>"热门文章",
      "children"=>array (
        array (
          "id"=>"83",
          "haschildren"=>"0",
          "reid"=>"12",
          "link"=>"/channel/weekly.html",
          "name"=>"一周",
          "children"=>array(),
          "code"=>"weekly",
          "type"=>"link",
        ),
        array (
          "id"=>"84",
          "haschildren"=>"0",
          "reid"=>"12",
          "link"=>"/channel/monthly.html",
          "name"=>"一月",
          "children"=>array(),
          "code"=>"monthly",
          "type"=>"link",
        ),
        array (
          "id"=>"85",
          "haschildren"=>"0",
          "reid"=>"12",
          "link"=>"/channel/quarterly.html",
          "name"=>"季度",
          "children"=>array (),
          "code"=>"quarterly",
          "type"=>"link",
        ),
        array (
          "id"=>"86",
          "haschildren"=>"0",
          "reid"=>"12",
          "link"=>"/channel/year.html",
          "name"=>"一年",
          "children"=>array (),
          "code"=>"year",
          "type"=>"link",
        ),
      ),
      "code"=>"weekly",
      "type"=>"link",
    ),
    array (
      "id"=>"13",
      "haschildren"=>"1",
      "reid"=>"1",
      "link"=>"/m/events/event.html",
      "name"=>"会议活动",
      "children"=>array (
        array (
          "id"=>"87",
          "haschildren"=>"0",
          "reid"=>"13",
          "link"=>"/m/events/recent.html",
          "name"=>"近期活动",
          "children"=>array(),
          "code"=>"eventupcoming",
          "type"=>"link",
        ),
        array (
          "id"=>"88",
          "haschildren"=>"0",
          "reid"=>"13",
          "link"=>"/index.php/events/previous",
          "name"=>"往期活动",
          "children"=>array (),
          "code"=>"eventprevious",
          "type"=>"link",
        ),
        array (
          "id"=>"89",
          "haschildren"=>"0",
          "reid"=>"13",
          "link"=>"/m/events/sponsorship.html",
          "name"=>"赞助活动",
          "children"=>array (),
          "code"=>"eventsponsorship",
          "type"=>"link",
        ),
        array (
          "id"=>"90",
          "haschildren"=>"0",
          "reid"=>"13",
          "link"=>"/m/events/aboutus.html",
          "name"=>"关于我们",
          "children"=>array (),
          "code"=>"eventabout",
          "type"=>"link",
        ),
      ),
      "code"=>"event",
      "type"=>"link",
    ),
    array (
      "id"=>"14",
      "haschildren"=>"0",
      "reid"=>"1",
      "link"=>"/marketing/home",
      "name"=>"会员信息中心",
      "children"=>array (),
      "code"=>"",
      "type"=>"link",
    ),
    array (
      "id"=>"111",
      "haschildren"=>"0",
      "reid"=>"1",
      "link"=>"http://www.ftchinese.com/m/marketing/intelligence.html",
      "name"=>"FT研究院",
      "children"=>array (),
      "code"=>"intelligence",
      "type"=>"link",
    ),
    array (
      "id"=>"15",
      "haschildren"=>"0",
      "reid"=>"1",
      "link"=>"/channel/mba.html",
      "name"=>"FT商学院",
      "children"=>array (),
      "code"=>"mba",
      "type"=>"channel",
    ),
    array (
      "id"=>"16",
      "haschildren"=>"0",
      "reid"=>"1",
      "link"=>"/channel/english.html",
      "name"=>"英语学习",
      "children"=>array (),
      "code"=>"english",
      "type"=>"link",
    ),
    array (
      "id"=>"17",
      "haschildren"=>"0",
      "reid"=>"1",
      "link"=>"/channel/slides.html",
      "name"=>"图辑",
      "children"=>array (),
      "code"=>"photo",
      "type"=>"link",
    ),
    array (
      "id"=>"18",
      "haschildren"=>"0",
      "reid"=>"1",
      "link"=>"/jobs/",
      "name"=>"职业机会",
      "children"=>array (),
      "code"=>"job",
      "type"=>"link",
    ),
    array (
      "id"=>"110",
      "haschildren"=>"0",
      "reid"=>"1",
      "link"=>"/channel/datanews.html",
      "name"=>"数据新闻",
      "children"=>array (),
      "code"=>"datanews",
      "type"=>"channel",
    ),
  ),
  "code"=>"home",
  "type"=>"link",
);

$china = array (
  "id"=>"2",
  "haschildren"=>"0",
  "reid"=>"0",
  "link"=>"/channel/china.html",
  "name"=>"中国",
  "children"=>array (
    array (
      "id"=>"19",
      "haschildren"=>"0",
      "reid"=>"2",
      "link"=>"/channel/chinareport.html",
      "name"=>"政经",
      "children"=>array (),
      "code"=>"chinareport",
      "type"=>"channel",
    ),
    array (
      "id"=>"20",
      "haschildren"=>"0",
      "reid"=>"2",
      "link"=>"/channel/chinabusiness.html",
      "name"=>"商业",
      "children"=>array (),
      "code"=>"chinabusiness",
      "type"=>"channel",
    ),
    array (
      "id"=>"21",
      "haschildren"=>"0",
      "reid"=>"2",
      "link"=>"/channel/chinamarkets.html",
      "name"=>"金融市场",
      "children"=>array (),
      "code"=>"chinamarkets",
      "type"=>"channel",
    ),
    array (
      "id"=>"22",
      "haschildren"=>"0",
      "reid"=>"2",
      "link"=>"/channel/chinastock.html",
      "name"=>"股市",
      "children"=>array (),
      "code"=>"chinastock",
      "type"=>"channel",
    ),
    array (
      "id"=>"23",
      "haschildren"=>"0",
      "reid"=>"2",
      "link"=>"/channel/chinaproperty.html",
      "name"=>"房地产",
      "children"=>array (),
      "code"=>"chinaproperty",
      "type"=>"channel",
    ),
    array (
      "id"=>"24",
      "haschildren"=>"0",
      "reid"=>"2",
      "link"=>"/channel/culture.html",
      "name"=>"社会与文化",
      "children"=>
      array (),
      "code"=>"culture",
      "type"=>"channel",
    ),
    array (
      "id"=>"25",
      "haschildren"=>"0",
      "reid"=>"2",
      "link"=>"/channel/chinaopinion.html",
      "name"=>"观点",
      "children"=>array (),
      "code"=>"chinaopinion",
      "type"=>"channel",
    )
  ),
  "code"=>"china",
  "type"=>"channel"
);

$global = array (
  "id"=>"3",
  "haschildren"=>"0",
  "reid"=>"0",
  "link"=>"/channel/world.html",
  "name"=>"全球",
  "children"=>array (
    array (
      "id"=>"26",
      "haschildren"=>"0",
      "reid"=>"3",
      "link"=>"/channel/usa.html",
      "name"=>"美国",
      "children"=>array (),
      "code"=>"usa",
      "type"=>"channel",
    ),
    array (
      "id"=>"27",
      "haschildren"=>"0",
      "reid"=>"3",
      "link"=>"/channel/uk.html",
      "name"=>"英国",
      "children"=>array (),
      "code"=>"uk",
      "type"=>"channel",
    ),
    array (
      "id"=>"28",
      "haschildren"=>"0",
      "reid"=>"3",
      "link"=>"/channel/asia.html",
      "name"=>"亚太",
      "children"=>array (),
      "code"=>"asia",
      "type"=>"channel",
    ),
    array (
      "id"=>"29",
      "haschildren"=>"0",
      "reid"=>"3",
      "link"=>"/channel/europe.html",
      "name"=>"欧洲",
      "children"=>array (),
      "code"=>"europe",
      "type"=>"channel",
    ),
    array (
      "id"=>"30",
      "haschildren"=>"0",
      "reid"=>"3",
      "link"=>"/channel/america.html",
      "name"=>"美洲",
      "children"=>array (),
      "code"=>"america",
      "type"=>"channel",
    ),
    array (
      "id"=>"31",
      "haschildren"=>"0",
      "reid"=>"3",
      "link"=>"/channel/africa.html",
      "name"=>"非洲",
      "children"=>array (),
      "code"=>"africa",
      "type"=>"channel",
    ),
  ),
  "code"=>"world",
  "type"=>"channel",
);

$economy = array (
  "id"=>"4",
  "haschildren"=>"0",
  "reid"=>"0",
  "link"=>"/channel/economy.html",
  "name"=>"经济",
  "children"=>array (
    array (
      "id"=>"32",
      "haschildren"=>"0",
      "reid"=>"4",
      "link"=>"/channel/globaleconomy.html",
      "name"=>"全球经济",
      "children"=>array (),
      "code"=>"globaleconomy",
      "type"=>"channel",
    ),
    array (
      "id"=>"33",
      "haschildren"=>"0",
      "reid"=>"4",
      "link"=>"/channel/chinaeconomy.html",
      "name"=>"中国经济",
      "children"=>array (),
      "code"=>"chinaeconomy",
      "type"=>"channel",
    ),
    array (
      "id"=>"34",
      "haschildren"=>"0",
      "reid"=>"4",
      "link"=>"/channel/trade.html",
      "name"=>"贸易",
      "children"=>array (),
      "code"=>"trade",
      "type"=>"channel",
    ),
    array (
      "id"=>"35",
      "haschildren"=>"0",
      "reid"=>"4",
      "link"=>"/channel/environment.html",
      "name"=>"环境",
      "children"=>array (),
      "code"=>"environment",
      "type"=>"channel",
    ),
    array (
      "id"=>"36",
      "haschildren"=>"0",
      "reid"=>"4",
      "link"=>"/channel/economics.html",
      "name"=>"经济评论",
      "children"=>array (),
      "code"=>"economics",
      "type"=>"channel",
    ),
  ),
  "code"=>"economy",
  "type"=>"channel",
);

$markets = array (
  "id"=>"5",
  "haschildren"=>"0",
  "reid"=>"0",
  "link"=>"/channel/markets.html",
  "name"=>"金融市场",
  "children"=>array (
    array (
      "id"=>"37",
      "haschildren"=>"0",
      "reid"=>"5",
      "link"=>"/channel/stock.html",
      "name"=>"股市",
      "children"=>array (),
      "code"=>"stock",
      "type"=>"channel",
    ),
    array (
      "id"=>"38",
      "haschildren"=>"0",
      "reid"=>"5",
      "link"=>"/channel/forex.html",
      "name"=>"外汇",
      "children"=>array (),
      "code"=>"forex",
      "type"=>"channel",
    ),
    array (
      "id"=>"39",
      "haschildren"=>"0",
      "reid"=>"5",
      "link"=>"/channel/bond.html",
      "name"=>"债市",
      "children"=>array (),
      "code"=>"bond",
      "type"=>"channel",
    ),
    array (
      "id"=>"40",
      "haschildren"=>"0",
      "reid"=>"5",
      "link"=>"/channel/commodity.html",
      "name"=>"大宗商品",
      "children"=>array (),
      "code"=>"commodity",
      "type"=>"channel",
    ),
    array (
      "id"=>"41",
      "haschildren"=>"0",
      "reid"=>"5",
      "link"=>"http://markets.ft.com/research/Markets/Overview",
      "name"=>"金融市场数据",
      "children"=>array (),
      "code"=>"",
      "type"=>"link",
    ),
  ),
  "code"=>"markets",
  "type"=>"channel",
);

$companies = array (
  "id"=>"6",
  "haschildren"=>"0",
  "reid"=>"0",
  "link"=>"/channel/business.html",
  "name"=>"商业",
  "children"=>array (
    array (
      "id"=>"42",
      "haschildren"=>"0",
      "reid"=>"6",
      "link"=>"/channel/finance.html",
      "name"=>"金融",
      "children"=>
      array (
        array (
          "id"=>"91",
          "haschildren"=>"0",
          "reid"=>"42",
          "link"=>"/tag/金融危机",
          "name"=>"金融危机",
          "children"=>array (),
          "code"=>"financialcrisis",
          "type"=>"link",
        ),
        array (
          "id"=>"92",
          "haschildren"=>"0",
          "reid"=>"42",
          "link"=>"/tag/银行业未来",
          "name"=>"银行业未来",
          "children"=>array (),
          "code"=>"futureofbank",
          "type"=>"link",
        ),
        array (
          "id"=>"93",
          "haschildren"=>"0",
          "reid"=>"42",
          "link"=>"/tag/资本主义",
          "name"=>"资本主义",
          "children"=>array (),
          "code"=>"capitalism",
          "type"=>"link",
        ),
      ),
      "code"=>"finance",
      "type"=>"channel",
    ),
    array (
      "id"=>"43",
      "haschildren"=>"0",
      "reid"=>"6",
      "link"=>"/channel/technology.html",
      "name"=>"科技",
      "children"=>array (),
      "code"=>"technology",
      "type"=>"channel",
    ),
    array (
      "id"=>"44",
      "haschildren"=>"0",
      "reid"=>"6",
      "link"=>"/channel/auto.html",
      "name"=>"汽车",
      "children"=>array (),
      "code"=>"auto",
      "type"=>"channel",
    ),
    array (
      "id"=>"45",
      "haschildren"=>"0",
      "reid"=>"6",
      "link"=>"/channel/property.html",
      "name"=>"房地产",
      "children"=>array (),
      "code"=>"property",
      "type"=>"channel",
    ),
    array (
      "id"=>"46",
      "haschildren"=>"0",
      "reid"=>"6",
      "link"=>"/channel/agriculture.html",
      "name"=>"农林",
      "children"=>array (),
      "code"=>"agriculture",
      "type"=>"channel",
    ),
    array (
      "id"=>"47",
      "haschildren"=>"0",
      "reid"=>"6",
      "link"=>"/channel/energy.html",
      "name"=>"能源",
      "children"=>array (),
      "code"=>"energy",
      "type"=>"channel",
    ),
    array (
      "id"=>"48",
      "haschildren"=>"0",
      "reid"=>"6",
      "link"=>"/channel/industrials.html",
      "name"=>"工业和采矿",
      "children"=>array (),
      "code"=>"industrials",
      "type"=>"channel",
    ),
    array (
      "id"=>"49",
      "haschildren"=>"0",
      "reid"=>"6",
      "link"=>"/channel/airline.html",
      "name"=>"航空和运输",
      "children"=>array (),
      "code"=>"airline",
      "type"=>"channel",
    ),
    array (
      "id"=>"50",
      "haschildren"=>"0",
      "reid"=>"6",
      "link"=>"/channel/pharma.html",
      "name"=>"医药",
      "children"=>array (),
      "code"=>"pharma",
      "type"=>"channel",
    ),
    array (
      "id"=>"51",
      "haschildren"=>"0",
      "reid"=>"6",
      "link"=>"/channel/entertainment.html",
      "name"=>"娱乐",
      "children"=>array (),
      "code"=>"entertainment",
      "type"=>"channel",
    ),
    array (
      "id"=>"52",
      "haschildren"=>"0",
      "reid"=>"6",
      "link"=>"/channel/consumer.html",
      "name"=>"零售和消费品",
      "children"=>array (),
      "code"=>"consumer",
      "type"=>"channel",
    ),
    array (
      "id"=>"53",
      "haschildren"=>"0",
      "reid"=>"6",
      "link"=>"/channel/media.html",
      "name"=>"传媒和文化",
      "children"=>array (),
      "code"=>"media",
      "type"=>"channel",
    ),
  ),
  "code"=>"business",
  "type"=>"channel",
);

$opinion = array (
  "id"=>"7",
  "haschildren"=>"0",
  "reid"=>"0",
  "link"=>"/channel/opinion.html",
  "name"=>"观点",
  "children"=>array (
    array (
      "id"=>"54",
      "haschildren"=>"0",
      "reid"=>"7",
      "link"=>"/channel/lex.html",
      "name"=>"Lex专栏",
      "children"=>array (),
      "code"=>"lex",
      "type"=>"channel",
    ),
    array (
      "id"=>"55",
      "haschildren"=>"0",
      "reid"=>"7",
      "link"=>"/channel/the-a-list.html",
      "name"=>"A-List",
      "children"=>array (),
      "code"=>"the-a-list",
      "type"=>"channel",
    ),
    array (
      "id"=>"56",
      "haschildren"=>"0",
      "reid"=>"7",
      "link"=>"/channel/column.html",
      "name"=>"专栏",
      "children"=>array (),
      "code"=>"column",
      "type"=>"channel",
    ),
    array (
      "id"=>"57",
      "haschildren"=>"0",
      "reid"=>"7",
      "link"=>"/channel/analysis.html",
      "name"=>"分析",
      "children"=>array (),
      "code"=>"analysis",
      "type"=>"channel",
    ),
    array (
      "id"=>"58",
      "haschildren"=>"0",
      "reid"=>"7",
      "link"=>"/channel/comment.html",
      "name"=>"评论",
      "children"=>array (),
      "code"=>"comment",
      "type"=>"channel",
    ),
    array (
      "id"=>"59",
      "haschildren"=>"0",
      "reid"=>"7",
      "link"=>"/channel/editorial.html",
      "name"=>"社评",
      "children"=>array (),
      "code"=>"editorial",
      "type"=>"channel",
    ),
    array (
      "id"=>"60",
      "haschildren"=>"0",
      "reid"=>"7",
      "link"=>"/channel/book.html",
      "name"=>"书评",
      "children"=>array (),
      "code"=>"book",
      "type"=>"channel",
    ),
    array (
      "id"=>"61",
      "haschildren"=>"0",
      "reid"=>"7",
      "link"=>"/channel/letter.html",
      "name"=>"读者有话说",
      "children"=>array (),
      "code"=>"letter",
      "type"=>"channel",
    ),
  ),
  "code"=>"opinion",
  "type"=>"channel",
);

$management = array (
  "id"=>"8",
  "haschildren"=>"0",
  "reid"=>"0",
  "link"=>"/channel/management.html",
  "name"=>"管理",
  "children"=>
  array (
    array (
      "id"=>"62",
      "haschildren"=>"0",
      "reid"=>"8",
      "link"=>"/channel/mba.html",
      "name"=>"FT商学院",
      "children"=>
      array (
        array (
          "id"=>"94",
          "haschildren"=>"0",
          "reid"=>"62",
          "link"=>"/channel/mbagym.html",
          "name"=>"互动教程",
          "children"=>array (),
          "code"=>"mbagym",
          "type"=>"channel",
        ),
        array (
          "id"=>"95",
          "haschildren"=>"0",
          "reid"=>"62",
          "link"=>"/channel/businesseducation.html",
          "name"=>"商业教育",
          "children"=>array (),
          "code"=>"businesseducation",
          "type"=>"channel",
        ),
        array (
          "id"=>"96",
          "haschildren"=>"0",
          "reid"=>"62",
          "link"=>"http://rankings.ft.com/businessschoolrankings/rankings",
          "name"=>"商学院排名",
          "children"=>array (),
          "code"=>"",
          "type"=>"link",
        ),
      ),
      "code"=>"mba",
      "type"=>"channel",
    ),
    array (
      "id"=>"63",
      "haschildren"=>"0",
      "reid"=>"8",
      "link"=>"/channel/career.html",
      "name"=>"职场",
      "children"=>
      array (
        array (
          "id"=>"97",
          "haschildren"=>"0",
          "reid"=>"63",
          "link"=>"/column/007000013",
          "name"=>"露西•凯拉韦专栏",
          "children"=>array (),
          "code"=>"lucy",
          "type"=>"link",
        ),
        array (
          "id"=>"98",
          "haschildren"=>"0",
          "reid"=>"63",
          "link"=>"/column/007000002",
          "name"=>"《朝九晚五》",
          "children"=>array (),
          "code"=>"shirley",
          "type"=>"link",
        ),
      ),
      "code"=>"career",
      "type"=>"channel",
    ),
    array (
      "id"=>"64",
      "haschildren"=>"0",
      "reid"=>"8",
      "link"=>"/channel/leadership.html",
      "name"=>"领导力",
      "children"=>
      array (
        array (
          "id"=>"99",
          "haschildren"=>"0",
          "reid"=>"64",
          "link"=>"/tag/创业",
          "name"=>"创业",
          "children"=>array (),
          "code"=>"startup",
          "type"=>"link",
        ),
        array (
          "id"=>"100",
          "haschildren"=>"0",
          "reid"=>"64",
          "link"=>"/tag/创新",
          "name"=>"创新",
          "children"=>array (),
          "code"=>"innovation",
          "type"=>"link",
        ),
        array (
          "id"=>"101",
          "haschildren"=>"0",
          "reid"=>"64",
          "link"=>"/column/007000034",
          "name"=>"卢克•约翰逊专栏",
          "children"=>array (),
          "code"=>"luke",
          "type"=>"link",
        ),
      ),
      "code"=>"leadership",
      "type"=>"channel",
    ),
    array (
      "id"=>"65",
      "haschildren"=>"0",
      "reid"=>"8",
      "link"=>"/tag/%E8%B4%A2%E5%AF%8C%E7%AE%A1%E7%90%86",
      "name"=>"财富管理",
      "children"=>array (),
      "code"=>"wealth",
      "type"=>"link",
    ),
    array (
      "id"=>"66",
      "haschildren"=>"0",
      "reid"=>"8",
      "link"=>"/tag/%E5%95%86%E5%8A%A1%E4%BA%92%E8%81%94",
      "name"=>"商务互联",
      "children"=>array (),
      "code"=>"connect",
      "type"=>"link",
    ),
    array (
      "id"=>"67",
      "haschildren"=>"0",
      "reid"=>"8",
      "link"=>"/channel/people.html",
      "name"=>"人物",
      "children"=>
      array (
        array (
          "id"=>"102",
          "haschildren"=>"0",
          "reid"=>"67",
          "link"=>"/tag/与FT共进午餐",
          "name"=>"与FT共进午餐",
          "children"=>array (),
          "code"=>"lunch",
          "type"=>"link",
        ),
        array (
          "id"=>"103",
          "haschildren"=>"0",
          "reid"=>"67",
          "link"=>"/tag/一周新闻人物",
          "name"=>"一周新闻人物",
          "children"=>array (),
          "code"=>"maninthenews",
          "type"=>"link",
        ),
        array (
          "id"=>"104",
          "haschildren"=>"0",
          "reid"=>"67",
          "link"=>"/tag/焦点女性",
          "name"=>"焦点女性",
          "children"=>array (),
          "code"=>"Womeninthenews",
          "type"=>"link",
        ),
        array (
          "id"=>"105",
          "haschildren"=>"0",
          "reid"=>"67",
          "link"=>"/topic/womenatthetop.html",
          "name"=>"巅峰女性",
          "children"=>array (),
          "code"=>"watt",
          "type"=>"link",
        ),
      ),
      "code"=>"people",
      "type"=>"channel",
    ),
  ),
  "code"=>"management",
  "type"=>"channel",
);

$lifestyle = array (
  "id"=>"9",
  "haschildren"=>"0",
  "reid"=>"0",
  "link"=>"/channel/lifestyle.html",
  "name"=>"生活时尚",
  "children"=>array (
    array (
      "id"=>"68",
      "haschildren"=>"0",
      "reid"=>"9",
      "link"=>"/channel/pursuit.html",
      "name"=>"乐尚街",
      "children"=>array (),
      "code"=>"pursuit",
      "type"=>"channel",
    ),
    array (
      "id"=>"69",
      "haschildren"=>"0",
      "reid"=>"9",
      "link"=>"/channel/taste.html",
      "name"=>"品味",
      "children"=>array (
        array (
          "id"=>"106",
          "haschildren"=>"0",
          "reid"=>"69",
          "link"=>"/column/007000050",
          "name"=>"简氏酒庄",
          "children"=>array (),
          "code"=>"robinson",
          "type"=>"link",
        ),
      ),
      "code"=>"taste",
      "type"=>"channel",
    ),
    array (
      "id"=>"70",
      "haschildren"=>"0",
      "reid"=>"9",
      "link"=>"/channel/travel.html",
      "name"=>"旅行",
      "children"=>array (
        array (
          "id"=>"107",
          "haschildren"=>"0",
          "reid"=>"70",
          "link"=>"/tag/商旅目的地",
          "name"=>"商旅目的地",
          "children"=>array (),
          "code"=>"destination",
          "type"=>"link",
        ),
      ),
      "code"=>"travel",
      "type"=>"channel",
    ),
    array (
      "id"=>"71",
      "haschildren"=>"0",
      "reid"=>"9",
      "link"=>"/channel/life.html",
      "name"=>"生活话题",
      "children"=>array (
        array (
          "id"=>"108",
          "haschildren"=>"0",
          "reid"=>"71",
          "link"=>"/column/007000046",
          "name"=>"《杏林守望者》",
          "children"=>array (),
          "code"=>"xinlin",
          "type"=>"link",
        ),
      ),
      "code"=>"life",
      "type"=>"channel",
    ),
    array (
      "id"=>"72",
      "haschildren"=>"0",
      "reid"=>"9",
      "link"=>"/channel/art.html",
      "name"=>"艺术与娱乐",
      "children"=>array (),
      "code"=>"art",
      "type"=>"channel",
    ),
    array (
      "id"=>"73",
      "haschildren"=>"0",
      "reid"=>"9",
      "link"=>"/channel/spend.html",
      "name"=>"消费经",
      "children"=>array (),
      "code"=>"spend",
      "type"=>"channel",
    ),
    array (
      "id"=>"74",
      "haschildren"=>"0",
      "reid"=>"9",
      "link"=>"/channel/money.html",
      "name"=>"理财",
      "children"=>array (
        array (
          "id"=>"109",
          "haschildren"=>"0",
          "reid"=>"74",
          "link"=>"/tag/艺术品投资",
          "name"=>"艺术品投资",
          "children"=>array (),
          "code"=>"artinvesting",
          "type"=>"link",
        ),
      ),
      "code"=>"money",
      "type"=>"channel",
    ),
  ),
  "code"=>"lifestyle",
  "type"=>"channel",
);

$stream = array (
  "id"=>"10",
  "haschildren"=>"0",
  "reid"=>"0",
  "link"=>"/channel/stream.html",
  "name"=>"视频",
  "children"=>array (
    array (
      "id"=>"75",
      "haschildren"=>"0",
      "reid"=>"10",
      "link"=>"/channel/vpolitics.html",
      "name"=>"政经",
      "children"=>array (),
      "code"=>"vpolitics",
      "type"=>"channel",
    ),
    array (
      "id"=>"76",
      "haschildren"=>"0",
      "reid"=>"10",
      "link"=>"/channel/vbusiness.html",
      "name"=>"产经",
      "children"=>array (),
      "code"=>"vbusiness",
      "type"=>"channel",
    ),
    array (
      "id"=>"77",
      "haschildren"=>"0",
      "reid"=>"10",
      "link"=>"/channel/vfinance.html",
      "name"=>"金融",
      "children"=>array (),
      "code"=>"vfinance",
      "type"=>"channel",
    ),
    array (
      "id"=>"78",
      "haschildren"=>"0",
      "reid"=>"10",
      "link"=>"/channel/vculture.html",
      "name"=>"文化",
      "children"=>array (),
      "code"=>"vculture",
      "type"=>"channel",
    ),
    array (
      "id"=>"79",
      "haschildren"=>"0",
      "reid"=>"10",
      "link"=>"/channel/videotinted.html",
      "name"=>"有色眼镜",
      "children"=>array (),
      "code"=>"videotinted",
      "type"=>"channel",
    ),
    array (
      "id"=>"112",
      "haschildren"=>"0",
      "reid"=>"10",
      "link"=>"/channel/explainer.html",
      "name"=>"秒懂",
      "children"=>array (),
      "code"=>"explainer",
      "type"=>"channel",
    ),
    array (
      "id"=>"113",
      "haschildren"=>"0",
      "reid"=>"10",
      "link"=>"/channel/viewtop.html",
      "name"=>"高端视点",
      "children"=>array (),
      "code"=>"viewtop",
      "type"=>"channel",
    ),
  ),
  "code"=>"stream",
  "type"=>"channel",
);

$data = [
	"odatalist"=>[
		$home, 
		$china, 
		$global, 
		$economy, 
		$markets, 
		$companies, 
		$opinion, 
		$management, 
		$lifestyle, 
		$stream
	]
];

$smarty->assign('datass1', $data);

$smarty->assign('topnav', 'china');
$smarty->assign('subnav', 'chinabusiness');

$smarty->display('../app/index.tpl');