/* jshint ignore:start */

window.languageOptions = [
  { value: 'zh-CN', name: '简体中文' },
  { value: 'zh-TW', name: '台灣正體' },
  { value: 'zh-HK', name: '香港繁體' },
  { value: 'en', name: 'English' },
  { value: 'es', name: 'Español' },
  { value: 'fr', name: 'Français' },
  { value: 'de', name: 'Deutsch' },
  { value: 'ja', name: '日本語' },
  { value: 'ko', name: '한국어' },
  { value: 'pt', name: 'Português' },
  { value: 'it', name: 'Italiano' },        
  { value: 'ru', name: 'Русский' }
];

const inductionData = {
  name: "user_induction",
  intro: "induction_intro",
  questions: [
    {
      text: "select_language",
      type: "single_choice",
      options: window.languageOptions,
      key: 'Language',
      variable: 'preferredLanguage',
      disable_input: true
    },
    {
      text: "select_follows",
      type: "multiple_choices",
      options: [
        {title: 'Regions', data: window.regions},
        {title: 'Sectors', data: window.sectors},
        {title: 'Genres', data: window.genres},
        {title: 'Popular', data: window.topics},
      ],
      disable_input: true
    },
    {
      text: "input_custom_interests",
      type: "custom_input",
      detail: "input_custom_interests_detail",
      disable_input: true
    }
  ]
};


const randomPromptDict = {
    greeting: {
      'en': [
        'Hello, how can I help you?',
        'Hi, how may I help you?',
        'Hello, how may I assist you?',
        'Greetings, how can I be of service?',
        'Hey there, how can I help you today?'
      ],
      'es': [
        'Hola, ¿en qué puedo ayudarte?',
        '¡Hola! ¿Cómo puedo ayudarte?',
        'Bienvenido, ¿en qué puedo ayudarte hoy?',
        '¿En qué puedo asistirte?',
        'Buenos días, ¿cómo puedo ayudarte?'
      ],
      'fr': [
        'Bonjour, comment puis-je vous aider ?',
        'Salut, comment puis-je vous aider ?',
        'Bonjour, en quoi puis-je vous aider ?',
        'Bonjour, que puis-je faire pour vous ?',
        'Bonjour, comment je peux vous aider aujourd\'hui ?'
      ],
      'de': [
        'Hallo, wie kann ich Ihnen helfen?',
        'Guten Tag, wie kann ich Ihnen helfen?',
        'Hallo, wie kann ich Ihnen behilflich sein?',
        'Guten Morgen, wie kann ich Ihnen helfen?',
        'Hi, was kann ich für Sie tun?'
      ],
      'ja': [
        'こんにちは、何かお手伝いできますか？',
        'はじめまして、何かご質問はありますか？',
        'お問い合わせありがとうございます。どういったことでお困りですか？',
        'こんにちは。何かお探しですか？',
        'こんにちは。ご相談はありますか？'
      ],
      'ko': [
        '안녕하세요, 무엇을 도와드릴까요?',
        '안녕하세요, 무엇이 문제인가요?',
        '안녕하세요, 무엇을 도와드릴까요?',
        '안녕하세요, 어떤 문제가 있으신가요?',
        '안녕하세요, 도움이 필요하시면 언제든지 말씀해주세요.'
      ],
      'pt': [
        'Olá, em que posso ajudar?',
        'Oi, como posso ajudar?',
        'Boa tarde, como posso ajudá-lo?',
        'Posso ajudar em alguma coisa?',
        'Olá, posso ajudar em algo?'
      ],
      'it': [
        'Ciao, come posso aiutarti?',
        'Salve, di cosa hai bisogno?',
        'Buongiorno, in che modo posso aiutarti?',
        'Ciao, posso aiutarti in qualche modo?',
        'Salve, di che hai bisogno?'
      ],
      'zh-TW': ['你好，有什麼可以幫助你的嗎？', '您好，需要我幫忙嗎？', '哈囉，有什麼我可以幫忙的嗎？', '您好，我能為您做些什麼？', '歡迎詢問，我有什麼可以幫忙的嗎？'],
      'zh-HK': ['你好，有什麼可以幫助你的嗎？', '您好，需要我幫忙嗎？', '哈囉，有什麼我可以幫忙的嗎？', '您好，我能為您做些什麼？', '歡迎詢問，我有什麼可以幫忙的嗎？'],
      'zh': [
        '你好，有什么需要帮助的吗？',
        '您好，需要我帮忙吗？',
        '你好，请问有什么可以帮您的？',
        '您好，我能为您提供什么服务？',
        '嗨，有什么我可以帮您的吗？'
      ],
      'ru': [
        'Здравствуйте, чем я могу вам помочь?',
        'Привет, чем я могу вам помочь?',
        'Здравствуйте, как я могу вам помочь?',
        'Приветствую, чем я могу быть полезен?',
        'Здравствуйте, чем я могу вам помочь сегодня?'
      ]
    },
    ending: {
      'en': [
      'What else can I do for you?',
      'Is there anything else I can assist you with?',
      'Do you require any further assistance from me?',
      'Are there any other ways I can be of service to you?',
      'Would you like me to do anything else for you?'
      ],
      'es': [
      '¿Qué más puedo hacer por ti?',
      '¿Hay algo más en lo que pueda ayudarte?',
      '¿Necesitas alguna otra asistencia de mi parte?',
      '¿Hay alguna otra manera en la que pueda ser de servicio para ti?',
      '¿Te gustaría que hiciera algo más por ti?'
      ],
      'fr': [
      `Que puis-je faire d'autre pour vous ?`,
      'Est-ce que je peux vous aider avec autre chose ?',
      `Avez-vous besoin d'une assistance supplémentaire de ma part ?`,
      `Y a-t-il d'autres moyens par lesquels je peux être utile pour vous ?`,
      'Voulez-vous que je fasse autre chose pour vous ?'
      ],
      'de': [
      'Was kann ich noch für Sie tun?',
      'Kann ich Ihnen noch in anderer Weise behilflich sein?',
      'Benötigen Sie weitere Unterstützung von mir?',
      'Gibt es noch andere Möglichkeiten, wie ich Ihnen dienen kann?',
      'Möchten Sie, dass ich noch etwas anderes für Sie tue?'
      ],
      'ja': [
      '他に何かご用件はありますか？',
      '他に何かお手伝いできることはありますか？',
      '私に他に何かお力になることはありますか？',
      '他にも何かお役に立てる方法はありますか？',
      '他に何かしてほしいことはありますか？'
      ],
      'ko': [
      '더 도와 드릴 게 있나요?',
      '다른 무언가 도와 드릴 수 있나요?',
      '제가 더 도움을 드릴 수 있는 것이 있나요?',
      '다른 방법으로도 봉사할 수 있는 게 있나요?',
      '제가 더 해 줄 일이 있나요?'
      ],
      'pt': [
      'O que mais posso fazer por você?',
      'Existe algo mais em que posso ajudá-lo?',
      'Você precisa de mais alguma assistência minha?',
      'Existem outras maneiras pelas quais posso ser útil para você?',
      'Você gostaria que eu fizesse algo mais por você?'
      ],
      'it': [
      'Cosa altro posso fare per te?',
      `C'è qualcos'altro in cui posso aiutarti?`,
      'Hai bisogno di ulteriore assistenza da parte mia?',
      'Ci sono altri modi in cui posso esserti utile?',
      'Desideri che io faccia altro per te?'
      ],
      'zh-TW': [
      '還有什麼我可以為您做的嗎？',
      '還有什麼我可以幫您的嗎？',
      '您需要我提供什麼其他的協助嗎？',
      '還有其他什麼方式我可以為您服務嗎？',
      '您還需要我為您做些什麼嗎？'
      ],
      'zh-HK': [
      '我還可以為您做些什麼嗎？',
      '還有什麼我可以協助您的嗎？',
      '您需要我提供其他的幫助嗎？',
      '還有其他方法可以令我為您服務嗎？',
      '您還需要我為您做其他事嗎？'
      ],
      'zh': [
      '还有什么我可以为您做的吗？',
      '还有什么我可以帮您的吗？',
      '您需要我提供什么其他的协助吗？',
      '还有其他什么方式我可以为您服务吗？',
      '您还需要我为您做些什么吗？'
      ],
      'ru': [
      'Чем еще я могу Вам помочь?',
      'Нужна ли Вам еще какая-либо помощь с моей стороны?',
      'Требуется ли Вам дополнительная помощь от меня?',
      'Есть ли другие способы, которыми я могу быть Вам полезен?',
      'Хотели бы Вы, чтобы я что-то еще сделал для Вас?'
      ]
    }
  };
  
let statusDictOriginal = {
  induction_intro: {
    zh: '欢迎访问FT！我是您的智能助理，将为您提供定制化的内容推荐。',
    en: 'Welcome to FT! I am your intelligent assistant, here to provide you with customized content recommendations.',
    es: '¡Bienvenido a FT! Soy tu asistente inteligente, aquí para ofrecerte recomendaciones de contenido personalizadas.',
    fr: 'Bienvenue chez FT! Je suis votre assistant intelligent, ici pour vous fournir des recommandations de contenu personnalisées.',
    de: 'Willkommen bei FT! Ich bin Ihr intelligenter Assistent, hier um Ihnen maßgeschneiderte Inhaltempfehlungen zu bieten.',
    ja: 'FTへようこそ！私はあなたのインテリジェントアシスタントで、カスタマイズされたコンテンツの推薦を提供します。',
    ko: 'FT에 오신 것을 환영합니다! 저는 여러분의 지능형 조수로, 맞춤형 콘텐츠 추천을 제공하겠습니다.',
    pt: 'Bem-vindo à FT! Sou seu assistente inteligente, aqui para fornecer recomendações de conteúdo personalizadas.',
    it: 'Benvenuto in FT! Sono il tuo assistente intelligente, qui per fornirti raccomandazioni di contenuto personalizzate.',
    'zh-TW': '歡迎訪問FT！我是您的智能助理，將為您提供定制化的內容推薦。',
    'zh-HK': '歡迎訪問FT！我是您的智能助理，將為您提供定制化的內容推薦。',
    ru: 'Добро пожаловать в FT! Я ваш умный помощник, здесь чтобы предложить вам персонализированные рекомендации по контенту.'
  },
  select_language: {
    zh: '请首先选择您喜欢的阅读语言。',
    en: 'Please first select your preferred reading language.',
    es: 'Por favor, seleccione primero su idioma de lectura preferido.',
    fr: `Veuillez d'abord sélectionner votre langue de lecture préférée.`,
    de: `Bitte wählen Sie zunächst Ihre bevorzugte Lesesprache aus.`,
    ja: 'まず、読みたい言語を選択してください。',
    ko: '먼저 선호하는 독서 언어를 선택해 주세요.',
    pt: 'Por favor, selecione primeiro o seu idioma de leitura preferido.',
    it: 'Si prega di selezionare prima la lingua di lettura preferita.',
    'zh-TW': '請首先選擇您喜歡的閱讀語言。',
    'zh-HK': '請首先選擇您喜歡的閱讀語言。',
    ru: 'Пожалуйста, сначала выберите предпочитаемый язык чтения.'
  },
  select_follows: {
    zh: '以下是FT的主要内容分类，您可以选择自己感兴趣的领域。',
    en: 'Here are the main content categories of FT. You can select the areas that interest you.',
    es: 'Aquí están las principales categorías de contenido de FT. Puede seleccionar las áreas que le interesan.',
    fr: 'Voici les principales catégories de contenu de FT. Vous pouvez sélectionner les domaines qui vous intéressent.',
    de: 'Hier sind die Hauptinhaltskategorien von FT. Sie können die Bereiche auswählen, die Sie interessieren.',
    ja: 'こちらがFTの主要なコンテンツカテゴリです。興味のある分野を選択できます。',
    ko: '다음은 FT의 주요 콘텐츠 카테고리입니다. 관심 있는 분야를 선택할 수 있습니다.',
    pt: 'Aqui estão as principais categorias de conteúdo da FT. Você pode selecionar as áreas que lhe interessam.',
    it: 'Ecco le principali categorie di contenuto di FT. Puoi selezionare le aree di tuo interesse.',
    'zh-TW': '以下是FT的主要內容分類，您可以選擇自己感興趣的領域。',
    'zh-HK': '以下是FT的主要內容分類，您可以選擇自己感興趣的領域。',
    ru: 'Вот основные категории контента FT. Вы можете выбрать интересующие вас области.'
  },
  input_custom_interests: {
    zh: '您是否有特别关注的话题？请在下方输入您感兴趣的关键词。',
    en: 'Do you have any specific topics of interest? Please enter your keywords below.',
    es: '¿Tiene algún tema de interés específico? Por favor, introduzca sus palabras clave a continuación.',
    fr: 'Avez-vous des sujets d’intérêt particuliers ? Veuillez saisir vos mots-clés ci-dessous.',
    de: 'Haben Sie spezielle Interessengebiete? Bitte geben Sie Ihre Schlüsselwörter unten ein.',
    ja: '特に関心のあるトピックはありますか？以下にキーワードを入力してください。',
    ko: '특별히 관심 있는 주제가 있으신가요? 아래에 키워드를 입력해 주세요.',
    pt: 'Você tem algum tópico de interesse específico? Por favor, insira suas palavras-chave abaixo.',
    it: 'Hai degli argomenti di interesse specifico? Inserisci le tue parole chiave qui sotto.',
    'zh-TW': '您是否有特別關注的話題？請在下方輸入您感興趣的關鍵詞。',
    'zh-HK': '您是否有特別關注的話題？請在下方輸入您感興趣的關鍵詞。',
    ru: 'Есть ли у вас конкретные темы, которые вас интересуют? Пожалуйста, введите ваши ключевые слова ниже.'
  },
  input_custom_interests_detail: {
    zh: '<p>您可以通过输入话题、类型、人物、地域、栏目、作者等关键词来定制您关注的FT内容，确保不错过任何重要资讯。</p><p>即使您关注的话题在FT没有对应的标签，你也可以关注自己输入的话题，让我们的人工智能语义搜索来协助您发现相关的最新内容。</p>',
    en: `<p>You can customize the FT content you follow by entering keywords such as topics, types, people, regions, columns, authors, etc., ensuring you don't miss any important information.</p><p>Even if the topic you are interested in doesn't have a direct label in FT, you can still follow it by entering it, and our AI semantic search will assist you in discovering the most relevant latest content.</p>`,
    es: `<p>Puede personalizar el contenido de FT que sigue introduciendo palabras clave como temas, tipos, personas, regiones, columnas, autores, etc., asegurándose de no perderse ninguna información importante.</p><p>Incluso si el tema que le interesa no tiene una etiqueta directa en FT, aún puede seguirlo ingresándolo, y nuestra búsqueda semántica de IA le ayudará a descubrir el contenido más reciente y relevante.</p>`,
    fr: `<p>Vous pouvez personnaliser le contenu FT que vous suivez en saisissant des mots-clés tels que sujets, types, personnes, régions, colonnes, auteurs, etc., pour ne manquer aucune information importante.</p><p>Même si le sujet qui vous intéresse n'a pas d'étiquette directe dans FT, vous pouvez le suivre en le saisissant, et notre recherche sémantique IA vous aidera à découvrir le contenu le plus pertinent et le plus récent.</p>`,
    de: '<p>Sie können den FT-Inhalt, den Sie verfolgen, anpassen, indem Sie Schlüsselwörter wie Themen, Typen, Personen, Regionen, Spalten, Autoren usw. eingeben, um sicherzustellen, dass Sie keine wichtigen Informationen verpassen.</p><p>Auch wenn das Thema, das Sie interessiert, keine direkte Kennzeichnung in FT hat, können Sie es dennoch verfolgen, indem Sie es eingeben, und unsere KI-basierte semantische Suche wird Ihnen helfen, die relevantesten neuesten Inhalte zu entdecken.</p>',
    ja: '<p>話題、タイプ、人物、地域、コラム、著者などのキーワードを入力することで、フォローしているFTコンテンツをカスタマイズし、重要な情報を逃さないようにできます。</p><p>興味のあるトピックにFT内で直接的なラベルがなくても、それを入力することでフォローでき、当社のAIセマンティック検索が最も関連性の高い最新コンテンツを発見するお手伝いをします。</p>',
    ko: '<p>주제, 유형, 인물, 지역, 칼럼, 저자 등의 키워드를 입력함으로써, 당신이 팔로우하는 FT 콘텐츠를 맞춤화하여 중요한 정보를 놓치지 않도록 할 수 있습니다.</p><p>관심 있는 주제에 FT에서 직접적인 라벨이 없더라도 그 주제를 입력하여 팔로우할 수 있으며, 우리의 AI 의미 검색이 가장 관련성 높은 최신 콘텐츠를 발견하는 데 도움을 줄 것입니다.</p>',
    pt: '<p>Você pode personalizar o conteúdo da FT que segue, inserindo palavras-chave como tópicos, tipos, pessoas, regiões, colunas, autores, etc., garantindo que você não perca nenhuma informação importante.</p><p>Mesmo que o tema de seu interesse não tenha uma etiqueta direta na FT, você ainda pode segui-lo inserindo-o, e nossa busca semântica de IA ajudará você a descobrir o conteúdo mais relevante e atualizado.</p>',
    it: `<p>Puoi personalizzare i contenuti FT che segui inserendo parole chiave come argomenti, tipi, persone, regioni, colonne, autori, ecc., per assicurarti di non perdere nessuna informazione importante.</p><p>Anche se l'argomento di tuo interesse non ha un'etichetta diretta in FT, puoi comunque seguirlo inserendolo, e la nostra ricerca semantica AI ti aiuterà a scoprire i contenuti più recenti e rilevanti.</p>`,
    'zh-TW': '<p>您可以透過輸入話題、類型、人物、地區、專欄、作者等關鍵詞來訂製您關注的FT內容，確保不錯過任何重要資訊。</p><p>即使您關注的話題在FT沒有對應的標籤，您也可以輸入自己關注的話題，讓我們的人工智能語義搜尋協助您發現相關的最新內容。</p>',
    'zh-HK': '<p>您可以透過輸入話題、類型、人物、地區、專欄、作者等關鍵詞來訂製您關注的FT內容，確保不錯過任何重要資訊。</p><p>即使您關注的話題在FT沒有對應的標籤，您也可以輸入自己關注的話題，讓我們的人工智能語義搜尋協助您發現相關的最新內容。</p>',
    ru: '<p>Вы можете настраивать содержание FT, которое вы следите, вводя ключевые слова, такие как темы, типы, люди, регионы, колонки, авторы и т. д., чтобы не пропустить никакой важной информации.</p><p>Даже если интересующая вас тема не имеет прямой метки в FT, вы можете следить за ней, вводя ее, и наш семантический поиск на базе ИИ поможет вам обнаружить наиболее актуальный и релевантный контент.</p>'
  },
  'Introduction': {
    en: 'Welcome to your personal finance and business news assistant! My goal is to help you get the most value out of your subscription by providing customized recommendations and insights. ',
    es: '¡Bienvenido a tu asistente personal de finanzas y noticias empresariales! Mi objetivo es ayudarte a obtener el mayor valor de tu suscripción mediante recomendaciones e ideas personalizadas.',
    fr: 'Bienvenue à votre assistant personnel pour les actualités financières et commerciales ! Mon objectif est de vous aider à tirer le meilleur parti de votre abonnement en vous fournissant des recommandations et des informations personnalisées.',
    de: 'Willkommen bei Ihrem persönlichen Finanz- und Wirtschaftsnachrichtenassistenten! Mein Ziel ist es, Ihnen durch maßgeschneiderte Empfehlungen und Einblicke den größten Nutzen aus Ihrem Abonnement zu verschaffen.',
    ja: 'ファイナンシャル・タイムズのパーソナル・ファイナンス＆ビジネスニュース・アシスタントへようこそ！私の目標は、カスタマイズされた推奨事項と洞察力を提供することで、あなたのサブスクリプションから最大の価値を得ることをお手伝いすることです。',
    ko: '개인 맞춤형 금융 및 비즈니스 뉴스 어시스턴트에 오신 것을 환영합니다! 나의 목표는 맞춤형 추천 및 인사이트를 제공하여 구독에서 최대 가치를 끌어내는 것입니다.',
    pt: 'Bem-vindo ao seu assistente pessoal de finanças e notícias empresariais! Meu objetivo é ajudá-lo a obter o máximo valor da sua assinatura, fornecendo recomendações e insights personalizados.',
    it: 'Benvenuto nel tuo assistente personale per le notizie finanziarie e commerciali! Il mio obiettivo è aiutarti a ottenere il massimo valore dalla tua sottoscrizione fornendo raccomandazioni e informazioni personalizzate.',
    'zh-TW': '歡迎使用專屬於您的財經新聞助理！我的目標是透過提供量身定制的建議和深度分析，協助您充分利用您的訂閱。',
    'zh-HK': '歡迎使用專屬於您的財經新聞助理！我的目標是透過提供量身定制的建議和深度分析，協助您充分利用您的訂閱。',
    zh: '欢迎使用专属于您的财经新闻助理！我的目标是通过提供量身定制的推荐和深度分析，协助您充分利用您的订阅。',
    ru: 'Добро пожаловать в вашего персонального помощника по финансовым и бизнес-новостям! Моя цель - помочь вам получить максимальную пользу от вашей подписки, предоставляя настраиваемые рекомендации и аналитику.'
  },
  'OtherReason': {
    en: 'Other reason',
    es: 'Otra razón',
    fr: 'Autre raison',
    de: 'Andere Gründe',
    ja: 'その他の理由',
    ko: '기타 이유',
    pt: 'Outro motivo',
    it: 'Altro motivo',
    'zh-TW': '其他原因',
    'zh-HK': '其他原因',
    zh: '其他原因',
    ru: 'Другая причина'
  },
  'Error': {
    en: 'Error',
    es: 'Error',
    fr: 'Erreur',
    de: 'Fehler',
    ja: 'エラー',
    ko: '오류',
    pt: 'Erro',
    it: 'Errore',
    'zh-TW': '錯誤',
    'zh-HK': '錯誤',
    zh: '错误',
    ru: 'Ошибка'
  },
  CustomerService: {
    zh: '帮助中心',
    en: 'Help Center',
    es: 'Centro de Ayuda',
    fr: `Centre d'Aide`,
    de: 'Hilfezentrum',
    ja: 'ヘルプセンター',
    ko: '도움말 센터',
    pt: 'Centro de Ajuda',
    it: 'Centro Assistenza',
    'zh-TW': '幫助中心',
    'zh-HK': '幫助中心',
    ru: 'Центр Поддержки'
  },
  ProcessingRequest: {
    en: 'Your request is being processed...',
    zh: '您的请求正在处理中...',
    es: 'Su solicitud está siendo procesada...',
    fr: 'Votre demande est en cours de traitement...',
    de: 'Ihre Anfrage wird bearbeitet...',
    ja: 'リクエストを処理中です...',
    ko: '요청이 처리 중입니다...',
    pt: 'Sua solicitação está sendo processada...',
    it: 'La tua richiesta è in elaborazione...',
    'zh-TW': '您的請求正在處理中...',
    'zh-HK': '您的請求正在處理中...',
    ru: 'Ваш запрос обрабатывается...'
  },
  NEXT: {
    en: 'NEXT',
    zh: '下一步',
    es: 'SIGUIENTE',
    fr: 'SUIVANT',
    de: 'WEITER',
    ja: '次へ',
    ko: '다음',
    pt: 'PRÓXIMO', 
    it: 'PROSSIMO',
    'zh-TW': '下一步',
    'zh-HK': '下一步',
    ru: 'ДАЛЕЕ'
  },
  FINISH: {
    en: 'FINISH',
    zh: '完成',
    es: 'FINALIZAR',
    fr: 'TERMINER',
    de: 'BEENDEN',
    ja: '終了',
    ko: '완료',
    pt: 'FINALIZAR',
    it: 'FINIRE',
    'zh-TW': '完成',
    'zh-HK': '完成',
    ru: 'ЗАВЕРШИТЬ'
  },
  'Top News For Me': {
    zh: '有什么值得我关注的要闻吗？',
    en: 'What are the top news for me?',
    es: '¿Cuáles son las noticias principales para mí?',
    fr: 'Quelles sont les principales nouvelles pour moi ?',
    de: 'Was sind die Top-Nachrichten für mich?',
    ja: '私にとってのトップニュースは何ですか？',
    ko: '내게 맞는 주요 뉴스는 무엇인가요?',
    pt: 'Quais são as principais notícias para mim?',
    it: 'Quali sono le principali notizie per me?',
    'zh-TW': '有什麼值得我關注的要聞嗎？',
    'zh-HK': '有什麼值得我關注的要聞嗎？',
    ru: 'Какие главные новости для меня?'
  },
  'Most Popular': {
    zh: 'FT上有哪些热门文章？',
    en: 'What are the most popular articles on the FT?',
    es: '¿Cuáles son los artículos más populares en el FT?',
    fr: 'Quels sont les articles les plus populaires sur le FT?',
    de: 'Was sind die beliebtesten Artikel auf der FT?',
    ja: 'FTで最も人気のある記事は何ですか？',
    ko: 'FT에서 가장 인기 있는 기사는 무엇인가요?',
    pt: 'Quais são os artigos mais populares no FT?',
    it: 'Quali sono gli articoli più popolari su FT?',
    'zh-TW': 'FT上有哪些熱門文章？',
    'zh-HK': 'FT上有哪些熱門文章？',
    ru: 'Какие самые популярные статьи в FT?'
  },
  'MyFT': {
    zh: '我的FT',
    en: 'MyFT',
    es: 'MiFT',
    fr: 'MonFT',
    de: 'MeinFT',
    ja: 'マイFT',
    ko: '마이FT',
    pt: 'MeuFT',
    it: 'MioFT',
    'zh-TW': '我的FT',
    'zh-HK': '我的FT',
    ru: 'МойFT'
  },
  'BackToTop': {
    zh: '从头开始',
    en: 'Start Over',
    es: 'Empezar de nuevo',
    fr: 'Recommencer',
    de: 'Von vorn beginnen',
    ja: '最初からやり直す',
    ko: '처음부터 다시 시작',
    pt: 'Começar de novo',
    it: 'Ricominciare',
    'zh-TW': '',
    'zh-HK': '',
    ru: 'Начать заново'
  },
  'DiscussArticle': {
    zh: '讨论文章',
    en: 'Discuss Article',
    es: 'Discutir Artículo',
    fr: `Discuter de l'article`,
    de: 'Artikel diskutieren',
    ja: '記事を議論する',
    ko: '글 논의',
    pt: 'Discutir Artigo',
    it: 'Discutere Articolo',
    'zh-TW': '討論文章',
    'zh-HK': '討論文章',
    ru: 'Обсудить статью'
  },
  'ChangeSubject': {
    en: 'Change Subject',
    zh:'改变话题',
    es: 'Cambiar Tema',
    fr: 'Changer de sujet',
    de: 'Thema ändern',
    ja: '話題を変える',
    ko: '주제 변경',
    pt: 'Mudar de assunto',
    it: 'Cambiare argomento',
    'zh-TW': '改變話題',
    'zh-HK': '改變話題',
    ru: 'Изменить тему'
  },
  'socratic': {
    zh: '苏格拉底诘问',
    en: 'Socratic Method',
    es: 'Método socrático',
    fr: 'Méthode socratique',
    de: 'Sokratische Methode',
    ja: 'ソクラテス式問い掛け法',
    ko: '소크라테스적 방법',
    pt: 'Método socrático',
    it: 'Metodo socratico',
    'zh-TW': '蘇格拉底質問',
    'zh-HK': '蘇格拉底式質問',
    ru: 'Сократический метод'
  },
  'SearchFTAPI': {
    en: 'Search FT',
    es: 'Buscar FT',
    fr: 'Rechercher FT',
    de: 'FT suchen',
    ja: 'FT検索',
    ko: 'FT 검색',
    pt: 'Pesquisar FT',
    it: 'Cerca FT',
    'zh-TW': '搜尋FT',
    'zh-HK': '搜尋FT',
    zh: '搜索FT',
    ru: 'Поиск FT'
  },
  'DiscussContent': {
    en: 'Talk about FT Content',
    zh: '讨论FT内容',
    es: 'Hablar sobre el contenido de FT',
    fr: 'Parler du contenu de FT',
    de: 'Über FT-Inhalte sprechen',
    ja: 'FTコンテンツについて話す',
    ko: 'FT 콘텐츠에 대해 이야기하다',
    pt: 'Falar sobre o conteúdo do FT',
    it: 'Parlare del contenuto di FT',
    'zh-TW': '討論FT內容',
    'zh-HK': '討論FT內容',
    ru: 'Обсуждение контента FT'
  },
  'Other': {
    en: 'Just Chat',
    es: 'Solo Chat',
    fr: 'Discussion',
    de: 'Nur Chatten',
    ja: 'チャットのみ',
    ko: '채팅만',
    pt: 'Apenas Bate-papo',
    it: 'Solo Chat',
    'zh-TW': '隨便聊聊',
    'zh-HK': '隨便聊聊',
    zh: '随便聊聊',
    ru: 'Просто чат'
  },
  Detail: {
    en: 'Detail',
    es: 'Detalle',
    fr: 'Détail',
    de: 'Detail',
    ja: '詳細',
    ko: '세부사항',
    pt: 'Detalhe',
    it: 'Dettaglio',
    'zh-TW': '詳細',
    'zh-HK': '詳情',
    zh: '详情',
    ru: 'Детали'
  },
  DetectingIntent: {
    zh: '正在尝试理解您的问题',
    en: 'Attempting to understand your question',
    es: 'Intentando entender su pregunta',
    fr: 'Tentative de comprendre votre question',
    de: 'Versuche, Ihre Frage zu verstehen',
    ja: 'ご質問を理解しようとしています',
    ko: '질문을 이해하려고 시도 중',
    pt: 'Tentando entender sua pergunta',
    it: 'Tentativo di capire la tua domanda',
    'zh-TW': '正在嘗試理解您的問題',
    'zh-HK': '正在嘗試理解您的問題',
    ru: 'Пытаюсь понять ваш вопрос'
  },
  GettingContext: {
    zh: '正在检查相关信息',
    en: 'Checking relevant information',
    es: 'Revisando la información relevante',
    fr: 'Vérification des informations pertinentes',
    de: 'Überprüfen relevanter Informationen',
    ja: '関連情報を確認しています',
    ko: '관련 정보 확인 중',
    pt: 'Verificando informações relevantes',
    it: 'Verificando le informazioni pertinenti',
    'zh-TW': '正在檢查相關信息',
    'zh-HK': '正在檢查相關信息',
    ru: 'Проверка соответствующей информации'
  },
  GettingContextFromDB: {
    zh: '在相关档案中进行检索，寻找和您的问题相关的内容',
    en: 'Retrieving from the database, looking for content related to your question',
    es: 'Recuperando de la base de datos, buscando contenido relacionado con su pregunta',
    fr: 'Récupération de la base de données, recherche de contenu lié à votre question',
    de: 'Abrufen aus der Datenbank, Suche nach Inhalten, die sich auf Ihre Frage beziehen',
    ja: 'データベースから情報を取得して、ご質問に関連する内容を探しています',
    ko: '데이터베이스에서 검색하여 귀하의 질문과 관련된 내용을 찾고 있습니다',
    pt: 'Recuperando do banco de dados, procurando conteúdo relacionado à sua pergunta',
    it: 'Recuperando dal database, cercando contenuti relativi alla tua domanda',
    'zh-TW': '在相關檔案中進行檢索，尋找和您的問題相關的內容',
    'zh-HK': '在相關檔案中進行檢索，尋找和您的問題相關的內容',
    ru: 'Извлекаю из базы данных, ищу содержание, связанное с вашим вопросом'
  },
  GettingResult: {
    zh: '让我再想一下',
    en: 'Let me think again',
    es: 'Déjame pensar de nuevo',
    fr: 'Laissez-moi réfléchir à nouveau',
    de: 'Lass mich nochmal überlegen',
    ja: 'もう一度考えさせてください',
    ko: '다시 생각해보겠습니다',
    pt: 'Deixe-me pensar novamente',
    it: 'Fammi pensare ancora',
    'zh-TW': '讓我再想一下',
    'zh-HK': '讓我再想一下',
    ru: 'Дайте мне подумать еще раз'
  },
  "Checking Content": {
    "en": "Checking Content...",
    "zh": "检查内容...",
    "es": "Verificando contenido...",
    "fr": "Vérification du contenu...",
    "de": "Inhalt prüfen...",
    "ja": "コンテンツを確認中...",
    "ko": "내용 확인 중...",
    "pt": "Verificando conteúdo...",
    "it": "Verifica del contenuto...",
    "zh-TW": "檢查內容...",
    "zh-HK": "檢查內容...",
    "ru": "Проверка содержимого..."
  },
  'No Search Result': {
    "zh": "很抱歉，没有找到符合条件的结果，请您更换一下搜索的条件，或者今后再试。",
    "en": "Sorry, no results were found that match your criteria. Please try changing your search terms or try again later.",
    "es": "Lo sentimos, no se encontraron resultados que coincidan con sus criterios. Intente cambiar sus términos de búsqueda o inténtelo de nuevo más tarde.",
    "fr": "Désolé, aucun résultat correspondant à vos critères n'a été trouvé. Veuillez essayer de modifier vos termes de recherche ou réessayez plus tard.",
    "de": "Entschuldigung, es wurden keine Ergebnisse gefunden, die Ihren Kriterien entsprechen. Bitte versuchen Sie, Ihre Suchbegriffe zu ändern oder versuchen Sie es später noch einmal.",
    "ja": "申し訳ありませんが、条件に合う結果が見つかりませんでした。検索条件を変更するか、後でもう一度試してください。",
    "ko": "죄송합니다, 기준에 맞는 결과를 찾을 수 없습니다. 검색 조건을 변경하거나 나중에 다시 시도해주세요.",
    "pt": "Desculpe, não foram encontrados resultados que correspondam aos seus critérios. Tente alterar os termos da pesquisa ou tente novamente mais tarde.",
    "it": "Spiacente, non sono stati trovati risultati che corrispondono ai tuoi criteri. Si prega di provare a cambiare i termini di ricerca o riprovare più tardi.",
    "zh-TW": "很抱歉，沒有找到符合條件的結果，請您更換一下搜索的條件，或者今後再試。",
    "zh-HK": "很抱歉，沒有找到符合條件的結果，請您更換一下搜尋的條件，或者稍後再試。",
    "ru": "Извините, не найдено результатов, соответствующих вашим критериям. Пожалуйста, попробуйте изменить условия поиска или повторите попытку позже."
  },
  'Final Score': {
    en: 'Final Score',
    es: 'Puntuación Final',
    fr: 'Score Final',
    de: 'Endstand',
    ja: '最終スコア',
    ko: '최종 점수',
    pt: 'Pontuação Final',
    it: 'Punteggio Finale',
    'zh-TW': '最終得分',
    'zh-HK': '最終得分',
    zh: '最终得分',
    ru: 'Итоговый счет'
  },
  'Ask Me': {
    en: 'Ask me about the latest in markets, economics, and politics...',
    es: 'Pregúntame sobre lo último en mercados, economía y política...',
    fr: `Demandez-moi les dernières nouvelles sur les marchés, l'économie et la politique...`,
    de: `Fragen Sie mich nach den neuesten Entwicklungen in Märkten, Wirtschaft und Politik...`,
    ja: '市場、経済、政治の最新情報について聞いてください...',
    ko: '시장, 경제, 정치에 대한 최신 정보를 물어보세요...',
    pt: 'Pergunte-me sobre as últimas novidades em mercados, economia e política...',
    it: `Chiedimi delle ultime novità sui mercati, l'economia e la politica...`,
    'zh-TW': '問我關於市場、經濟和政治的最新消息...',
    'zh-HK': '問我關於市場、經濟和政治的最新消息...',
    zh: '问我关于市场、经济和政治的最新消息...',
    ru: 'Спросите меня о последних новостях на рынках, в экономике и политике...'
  },
  'byline': {
    zh: '作者',
    en: 'author',
    es: 'autor',
    fr: 'auteur',
    de: 'Autor',
    ja: '著者',
    ko: '저자',
    pt: 'autor',
    it: 'autore',
    'zh-TW': '作者',
    'zh-HK': '作者',
    ru: 'автор'
},
'people': {
    en: 'people',
    zh: '人物',
    es: 'personas',
    fr: 'personnes',
    de: 'Personen',
    ja: '人々',
    ko: '사람들',
    pt: 'pessoas',
    it: 'persone',
    'zh-TW': '人物',
    'zh-HK': '人物',
    ru: 'люди'
},
'organisations': {
    en: 'organisation',
    zh: '组织',
    es: 'organización',
    fr: 'organisation',
    de: 'Organisation',
    ja: '組織',
    ko: '조직',
    pt: 'organização',
    it: 'organizzazione',
    'zh-TW': '組織',
    'zh-HK': '組織',
    ru: 'организация'
},
'brand': {
  en: 'brand',
  zh: '品牌',
  es: 'marca',
  fr: 'marque',
  de: 'Marke',
  ja: 'ブランド',
  ko: '브랜드',
  pt: 'marca',
  it: 'marca',
  'zh-TW': '品牌',
  'zh-HK': '品牌',
  ru: 'бренд'
},
'genre': {
  en: 'genre',
  zh: '类型',
  es: 'género',
  fr: 'genre',
  de: 'Genre',
  ja: 'ジャンル',
  ko: '장르',
  pt: 'gênero',
  it: 'genere',
  'zh-TW': '類型',
  'zh-HK': '類型',
  ru: 'жанр'
},
'Sectors': {
  'en': 'Sectors',
  'zh': '板块',
  'es': 'Sectores',
  'fr': 'Secteurs',
  'de': 'Sektoren',
  'ja': 'セクター',
  'ko': '섹터',
  'pt': 'Setores',
  'it': 'Settori',
  'zh-TW': '板塊',
  'zh-HK': '板塊',
  'ru': 'Сектора'
},
Genres: {
  'en': 'Genres',
  'zh': '类型',
  'es': 'Géneros',
  'fr': 'Genres',
  'de': 'Genres',
  'ja': 'ジャンル',
  'ko': '장르',
  'pt': 'Gêneros',
  'it': 'Generi',
  'zh-TW': '類型',
  'zh-HK': '類型',
  'ru': 'Жанры'
},
'<!--space-->': {
  en: ' ',
  zh: '',
  es: ' ',
  fr: ' ',
  de: ' ',
  ja: '',
  ko: '',
  pt: ' ',
  it: ' ',
  'zh-TW': '',
  'zh-HK': '',
  ru: ' '
},
'Quiz Me': {
    en: 'Test my understanding',
    es: 'Prueba mi comprensión',
    fr: 'Testez ma compréhension',
    de: 'Teste mein Verständnis',
    ja: '私の理解をテストしてください',
    ko: '내 이해를 테스트하세요',
    pt: 'Teste a minha compreensão',
    it: 'Testa la mia comprensione',
    'zh-TW': '測試我的理解',
    'zh-HK': '測試我的理解',
    zh: '测试我的理解',
    ru: 'Проверьте мое понимание'
  },
  'Socratic Method': {
    zh: '苏格拉底诘问',
    en: 'Socratic method',
    es: 'Método socrático',
    fr: 'Méthode socratique',
    de: 'Sokratische Methode',
    ja: 'ソクラテス式問い掛け法',
    ko: '소크라테스적 방법',
    pt: 'Método socrático',
    it: 'Metodo socratico',
    'zh-TW': '蘇格拉底質問',
    'zh-HK': '蘇格拉底式質問',
    ru: 'Сократический метод'
  },
  'Socratic Method Explained': {
    en: 'The Socratic Method is a way of questioning and discussing ideas to challenge assumptions and arrive at a better understanding. It involves asking questions to uncover underlying beliefs and test the logic of responses given. It is used to promote critical thinking, problem-solving, and creativity in various fields.',
    zh: '苏格拉底诘问方法是一种质疑和讨论观念的方式，旨在挑战假设并达到更好的理解。它涉及提出问题以揭示潜在信念并测试所给出的响应的逻辑。它用于在各个领域中促进批判性思维、问题解决和创造力。',
    es: 'El Método Socrático es una forma de cuestionar y discutir ideas para desafiar suposiciones y llegar a una mejor comprensión. Implica hacer preguntas para descubrir creencias subyacentes y poner a prueba la lógica de las respuestas dadas. Se utiliza para promover el pensamiento crítico, la resolución de problemas y la creatividad en varios campos.',
    fr: 'La méthode socratique est une façon de questionner et de discuter des idées afin de remettre en question les hypothèses et parvenir à une meilleure compréhension. Elle consiste à poser des questions pour découvrir les croyances sous-jacentes et tester la logique des réponses données. Elle est utilisée pour promouvoir la pensée critique, la résolution de problèmes et la créativité dans différents domaines.',
    de: 'Die sokratische Methode ist eine Art des Fragens und Diskutierens von Ideen, um Annahmen herauszufordern und zu einem besseren Verständnis zu gelangen. Es beinhaltet Fragen, um zugrunde liegende Überzeugungen aufzudecken und die Logik der gegebenen Antworten zu prüfen. Es wird verwendet, um kritisches Denken, Problemlösung und Kreativität in verschiedenen Bereichen zu fördern.',
    ja: 'ソクラテスの方法は、仮定に挑戦し、より良い理解に到達するための問いかけと議論の方法です。潜在的な信念を明らかにするために質問し、回答の論理をテストすることが含まれます。さまざまな分野で批判的思考、問題解決、創造性を促進するために使用されています。',
    ko: '소크라테스 방법은 가정을 도전하고 더 나은 이해를 도출하기 위해 아이디어에 대한 질문과 토론하는 방법입니다. 대답의 논리를 검증하고, 깔끔하지 않은 논리를 깨우쳐 신념을 드러냅니다. 다양한 분야에서 비판적 사고, 문제 해결 및 창의성을 촉진하는 데 사용됩니다.',
    pt: 'O Método Socrático é uma maneira de questionar e discutir ideias para desafiar pressupostos e chegar a uma melhor compreensão. Envolve fazer perguntas para descobrir crenças subjacentes e testar a lógica das respostas dadas. É usado para promover o pensamento crítico, a resolução de problemas e a criatividade em várias áreas.',
    it: `Il Metodo Socratico è un modo di interrogare e discutere le idee per mettere in discussione le assunzioni e arrivare ad una migliore comprensione. Comprende l'arte di porre domande per scoprire le credenze sottostanti e testare la logica delle risposte date. È utilizzato per promuovere il pensiero critico, la risoluzione dei problemi e la creatività in vari campi.`,
    'zh-TW': '蘇格拉底詰問方法是一種質疑和討論觀念的方式，旨在挑戰假設並達到更好的理解。它涉及提出問題以揭示潛在信念並測試所給出的回應的邏輯。它用於在各個領域中促進批判性思維、問題解決和創造力。',
    'zh-HK': '蘇格拉底詰問方法是一種質疑和討論觀念的方式，旨在挑戰假設並達到更好的理解。它涉及提出問題以揭示潛在信念並測試所給出的回應的邏輯。它用於在各個領域中促進批判性思維、問題解決和創造力。',
    ru: 'Метод Сократа - это способ вопросительного и обсуждающего подхода к идеям, направленный на оспаривание предположений и достижение лучшего понимания. Он включает в себя задавание вопросов, чтобы раскрыть скрытые убеждения и проверить логику полученных ответов. Используется для развития критического мышления, решения проблем и креативности в различных областях.'
  },
  Regions: {
    en: 'Regions',
    es: 'Regiones',
    fr: 'Régions',
    de: 'Regionen',
    ja: '地域',
    ko: '지역',
    pt: 'Regiões',
    it: 'Regioni',
    ru: 'Регионы',
    'zh-TW': '地區',
    'zh-HK': '地區',
    zh: '地区'
  },
  China: {
    en: 'China',
    es: 'China',
    fr: 'Chine',
    de: 'China',
    ja: '中国',
    ko: '중국',
    pt: 'China',
    it: 'Cina',
    ru: 'Китай',
    'zh-TW': '中國',
    'zh-HK': '中國',
    zh: '中国'
  },
  'United States': {
    en: 'United States',
    es: 'Estados Unidos',
    fr: 'États-Unis',
    de: 'Vereinigte Staaten',
    ja: 'アメリカ合衆国',
    ko: '미국',
    pt: 'Estados Unidos',
    it: 'Stati Uniti',
    ru: 'Соединённые Штаты',
    zh: '美国',
    'zh-TW': '美國',
    'zh-HK': '美國'
  },
  'Japan': {
    en: 'Japan',
    es: 'Japón',
    fr: 'Japon',
    de: 'Japan',
    ja: '日本',
    ko: '일본',
    pt: 'Japão',
    it: 'Giappone',
    ru: 'Япония',
    zh: '日本',
    'zh-TW': '日本',
    'zh-HK': '日本'
  },
  'Germany': {
    en: 'Germany',
    es: 'Alemania',
    fr: 'Allemagne',
    de: 'Deutschland',
    ja: 'ドイツ',
    ko: '독일',
    pt: 'Alemanha',
    it: 'Germania',
    ru: 'Германия',
    zh: '德国',
    'zh-TW': '德國',
    'zh-HK': '德國'
  },
  'India': {
    en: 'India',
    es: 'India',
    fr: 'Inde',
    de: 'Indien',
    ja: 'インド',
    ko: '인도',
    pt: 'Índia',
    it: 'India',
    ru: 'Индия',
    zh: '印度',
    'zh-TW': '印度',
    'zh-HK': '印度'
  },
  'France': {
    en: 'France',
    es: 'Francia',
    fr: 'France',
    de: 'Frankreich',
    ja: 'フランス',
    ko: '프랑스',
    pt: 'França',
    it: 'Francia',
    ru: 'Франция',
    zh: '法国',
    'zh-TW': '法國',
    'zh-HK': '法國'
  },
  'Brazil': {
    en: 'Brazil',
    es: 'Brasil',
    fr: 'Brésil',
    de: 'Brasilien',
    ja: 'ブラジル',
    ko: '브라질',
    pt: 'Brasil',
    it: 'Brasile',
    ru: 'Бразилия',
    zh: '巴西',
    'zh-TW': '巴西',
    'zh-HK': '巴西'
  },
  'Russia': {
    en: 'Russia',
    es: 'Rusia',
    fr: 'Russie',
    de: 'Russland',
    ja: 'ロシア',
    ko: '러시아',
    pt: 'Rússia',
    it: 'Russia',
    ru: 'Россия',
    zh: '俄罗斯',
    'zh-TW': '俄國',
    'zh-HK': '俄羅斯'
  },  
  'Canada': {
    en: 'Canada',
    es: 'Canadá',
    fr: 'Canada',
    de: 'Kanada',
    ja: 'カナダ',
    ko: '캐나다',
    pt: 'Canadá',
    it: 'Canada',
    ru: 'Канада',
    zh: '加拿大',
    'zh-TW': '加拿大',
    'zh-HK': '加拿大'
  },
  'Australia': {
    en: 'Australia',
    es: 'Australia',
    fr: 'Australie',
    de: 'Australien',
    ja: 'オーストラリア',
    ko: '오스트레일리아',
    pt: 'Austrália',
    it: 'Australia',
    ru: 'Австралия',
    zh: '澳大利亚',
    'zh-TW': '澳洲',
    'zh-HK': '澳洲'
  },
  'South Africa': {
    en: 'South Africa',
    es: 'Sudáfrica',
    fr: 'Afrique du Sud',
    de: 'Südafrika',
    ja: '南アフリカ',
    ko: '남아프리카 공화국',
    pt: 'África do Sul',
    it: 'Sud Africa',
    ru: 'Южная Африка',
    zh: '南非',
    'zh-TW': '南非',
    'zh-HK': '南非'
    },
    'South Korea': {
    en: 'South Korea',
    es: 'Corea del Sur',
    fr: 'Corée du Sud',
    de: 'Südkorea',
    ja: '大韓民国',
    ko: '한국',
    pt: 'Coreia do Sul',
    it: 'Corea del Sud',
    ru: 'Южная Корея',
    zh: '韩国',
    'zh-TW': '南韓',
    'zh-HK': '南韓'
  },
  'Spain': {
    en: 'Spain',
    es: 'España',
    fr: 'Espagne',
    de: 'Spanien',
    ja: 'スペイン',
    ko: '스페인',
    pt: 'Espanha',
    it: 'Spagna',
    ru: 'Испания',
    zh: '西班牙',
    'zh-TW': '西班牙',
    'zh-HK': '西班牙'
  },
  'United Kingdom': {
    en: 'United Kingdom',
    es: 'Reino Unido',
    fr: 'Royaume-Uni',
    de: 'Vereinigtes Königreich',
    ja: 'イギリス',
    ko: '영국',
    pt: 'Reino Unido',
    it: 'Regno Unito',
    ru: 'Великобритания',
    zh: '英国',
    'zh-TW': '英國',
    'zh-HK': '英國'
  },
  'Italy': {
    en: 'Italy',
    es: 'Italia',
    fr: 'Italie',
    de: 'Italien',
    ja: 'イタリア',
    ko: '이탈리아',
    pt: 'Itália',
    it: 'Italia',
    ru: 'Италия',
    zh: '意大利',
    'zh-TW': '義大利',
    'zh-HK': '意大利'
  },
  'Mexico': {
    en: 'Mexico',
    es: 'México',
    fr: 'Mexique',
    de: 'Mexiko',
    ja: 'メキシコ',
    ko: '멕시코',
    pt: 'México',
    it: 'Messico',
    ru: 'Мексика',
    zh: '墨西哥',
    'zh-TW': '墨西哥',
    'zh-HK': '墨西哥'
  },
  'Indonesia': {
    en: 'Indonesia',
    es: 'Indonesia',
    fr: 'Indonésie',
    de: 'Indonesien',
    ja: 'インドネシア',
    ko: '인도네시아',
    pt: 'Indonésia',
    it: 'Indonesia',
    ru: 'Индонезия',
    zh: '印度尼西亚',
    'zh-TW': '印尼',
    'zh-HK': '印尼'
  },
  'Turkey': {
    en: 'Turkey',
    es: 'Turquía',
    fr: 'Turquie',
    de: 'Türkei',
    ja: 'トルコ',
    ko: '터키',
    pt: 'Turquia',
    it: 'Turchia',
    ru: 'Турция',
    zh: '土耳其',
    'zh-TW': '土耳其',
    'zh-HK': '土耳其'
  },
  'Netherlands': {
    en: 'Netherlands',
    es: 'Países Bajos',
    fr: 'Pays-Bas',
    de: 'Niederlande',
    ja: 'オランダ',
    ko: '네덜란드',
    pt: 'Holanda',
    it: 'Paesi Bassi',
    ru: 'Нидерланды',
    zh: '荷兰',
    'zh-TW': '荷蘭',
    'zh-HK': '荷蘭'
  },
  'Saudi Arabia': {
    en: 'Saudi Arabia',
    es: 'Arabia Saudita',
    fr: 'Arabie saoudite',
    de: 'Saudi-Arabien',
    ja: 'サウジアラビア',
    ko: '사우디아라비아',
    pt: 'Arábia Saudita',
    it: 'Arabia Saudita',
    ru: 'Саудовская Аравия',
    zh: '沙特阿拉伯',
    'zh-TW': '沙烏地阿拉伯',
    'zh-HK': '沙特阿拉伯'
  },
  'Switzerland': {
    en: 'Switzerland',
    es: 'Suiza',
    fr: 'Suisse',
    de: 'Schweiz',
    ja: 'スイス',
    ko: '스위스',
    pt: 'Suíça',
    it: 'Svizzera',
    ru: 'Швейцария',
    zh: '瑞士',
    'zh-TW': '瑞士',
    'zh-HK': '瑞士'
  },
  'Sweden': {
    en: 'Sweden',
    es: 'Suecia',
    fr: 'Suède',
    de: 'Schweden',
    ja: 'スウェーデン',
    ko: '스웨덴',
    pt: 'Suécia',
    it: 'Svezia',
    ru: 'Швеция',
    zh: '瑞典',
    'zh-TW': '瑞典',
    'zh-HK': '瑞典'
  },
  'Nigeria': {
    en: 'Nigeria',
    es: 'Nigeria',
    fr: 'Nigéria',
    de: 'Nigeria',
    ja: 'ナイジェリア',
    ko: '나이지리아',
    pt: 'Nigéria',
    it: 'Nigeria',
    ru: 'Нигерия',
    zh: '尼日利亚',
    'zh-TW': '奈及利亞',
    'zh-HK': '尼日利亚'
  },
  'Poland': {
    en: 'Poland',
    es: 'Polonia',
    fr: 'Pologne',
    de: 'Polen',
    ja: 'ポーランド',
    ko: '폴란드',
    pt: 'Polônia',
    it: 'Polonia',
    ru: 'Польша',
    zh: '波兰',
    'zh-TW': '波蘭',
    'zh-HK': '波兰'
  },
  'Argentina': {
    en: 'Argentina',
    es: 'Argentina',
    fr: 'Argentine',
    de: 'Argentinien',
    ja: 'アルゼンチン',
    ko: '아르헨티나',
    pt: 'Argentina',
    it: 'Argentina',
    ru: 'Аргентина',
    zh: '阿根廷',
    'zh-TW': '阿根廷',
    'zh-HK': '阿根廷'
  },
  'Norway': {
    en: 'Norway',
    es: 'Noruega',
    fr: 'Norvège',
    de: 'Norwegen',
    ja: 'ノルウェー',
    ko: '노르웨이',
    pt: 'Noruega',
    it: 'Norvegia',
    ru: 'Норвегия',
    zh: '挪威',
    'zh-TW': '挪威',
    'zh-HK': '挪威'
  },
  'Iran': {
    en: 'Iran',
    es: 'Irán',
    fr: 'Iran',
    de: 'Iran',
    ja: 'イラン',
    ko: '이란',
    pt: 'Irã',
    it: 'Iran',
    ru: 'Иран',
    zh: '伊朗',
    'zh-TW': '伊朗',
    'zh-HK': '伊朗'
  },
  'Egypt': {
    en: 'Egypt',
    es: 'Egipto',
    fr: 'Égypte',
    de: 'Ägypten',
    ja: 'エジプト',
    ko: '이집트',
    pt: 'Egito',
    it: 'Egitto',
    ru: 'Египет',
    zh: '埃及',
    'zh-TW': '埃及',
    'zh-HK': '埃及'
  },
    'Belgium': {
    en: 'Belgium',
    es: 'Bélgica',
    fr: 'Belgique',
    de: 'Belgien',
    ja: 'ベルギー',
    ko: '벨기에',
    pt: 'Bélgica',
    it: 'Belgio',
    ru: 'Бельгия',
    zh: '比利时',
    'zh-TW': '比利時',
    'zh-HK': '比利時'
  },
  'Bangladesh': {
    en: 'Bangladesh',
    es: 'Bangladesh',
    fr: 'Bangladesh',
    de: 'Bangladesch',
    ja: 'バングラデシュ',
    ko: '방글라데시',
    pt: 'Bangladesh',
    it: 'Bangladesh',
    ru: 'Бангладеш',
    zh: '孟加拉国',
    'zh-TW': '孟加拉',
    'zh-HK': '孟加拉'
  },
  'Thailand': {
    en: 'Thailand',
    es: 'Tailandia',
    fr: 'Thaïlande',
    de: 'Thailand',
    ja: 'タイ',
    ko: '태국',
    pt: 'Tailândia',
    it: 'Tailandia',
    ru: 'Таиланд',
    zh: '泰国',
    'zh-TW': '泰國',
    'zh-HK': '泰國'
  },
  'Greece': {
    en: 'Greece',
    es: 'Grecia',
    fr: 'Grèce',
    de: 'Griechenland',
    ja: 'ギリシャ',
    ko: '그리스',
    pt: 'Grécia',
    it: 'Grecia',
    ru: 'Греция',
    zh: '希腊',
    'zh-TW': '希臘',
    'zh-HK': '希臘'
  },
  'Pakistan': {
    en: 'Pakistan',
    es: 'Pakistán',
    fr: 'Pakistan',
    de: 'Pakistan',
    ja: 'パキスタン',
    ko: '파키스탄',
    pt: 'Paquistão',
    it: 'Pakistan',
    ru: 'Пакистан',
    zh: '巴基斯坦',
    'zh-TW': '巴基斯坦',
    'zh-HK': '巴基斯坦'
  },
  'Vietnam': {
    en: 'Vietnam',
    es: 'Vietnam',
    fr: 'Vietnam',
    de: 'Vietnam',
    ja: 'ベトナム',
    ko: '베트남',
    pt: 'Vietnã',
    it: 'Vietnam',
    ru: 'Вьетнам',
    zh: '越南',
    'zh-TW': '越南',
    'zh-HK': '越南'
  },
  'Philippines': {
    en: 'Philippines',
    es: 'Filipinas',
    fr: 'Philippines',
    de: 'Philippinen',
    ja: 'フィリピン',
    ko: '필리핀',
    pt: 'Filipinas',
    it: 'Filippine',
    ru: 'Филиппины',
    zh: '菲律宾',
    'zh-TW': '菲律賓',
    'zh-HK': '菲律宾'
  },
  'New Zealand': {
    en: 'New Zealand',
    es: 'Nueva Zelanda',
    fr: 'Nouvelle-Zélande',
    de: 'Neuseeland',
    ja: 'ニュージーランド',
    ko: '뉴질랜드',
    pt: 'Nova Zelândia',
    it: 'Nuova Zelanda',
    ru: 'Новая Зеландия',
    zh: '新西兰',
    'zh-TW': '紐西蘭',
    'zh-HK': '新西兰'
  },
  'Malaysia': {
    en: 'Malaysia',
    es: 'Malasia',
    fr: 'Malaisie',
    de: 'Malaysia',
    ja: 'マレーシア',
    ko: '말레이시아',
    pt: 'Malásia',
    it: 'Malesia',
    ru: 'Малайзия',
    zh: '马来西亚',
    'zh-TW': '馬來西亞',
    'zh-HK': '馬來西亞'
  },  
  'Ukraine': {
    en: 'Ukraine',
    es: 'Ucrania',
    fr: 'Ukraine',
    de: 'Ukraine',
    ja: 'ウクライナ',
    ko: '우크라이나',
    pt: 'Ucrânia',
    it: 'Ucraina',
    ru: 'Украина',
    zh: '乌克兰',
    'zh-TW': '烏克蘭',
    'zh-HK': '乌克兰'
  },
  'Europe': {
    en: 'Europe',
    es: 'Europa',
    fr: 'Europe',
    de: 'Europa',
    ja: 'ヨーロッパ',
    ko: '유럽',
    pt: 'Europa',
    it: 'Europa',
    ru: 'Европа',
    zh: '欧洲',
    'zh-TW': '歐洲',
    'zh-HK': '歐洲'
  },
  'Singapore': {
    en: 'Singapore',
    es: 'Singapur',
    fr: 'Singapour',
    de: 'Singapur',
    ja: 'シンガポール',
    ko: '싱가포르',
    pt: 'Singapura',
    it: 'Singapore',
    ru: 'Сингапур',
    zh: '新加坡',
    'zh-TW': '新加坡',
    'zh-HK': '新加坡'
  },
  'Israel': {
    en: 'Israel',
    es: 'Israel',
    fr: 'Israël',
    de: 'Israel',
    ja: 'イスラエル',
    ko: '이스라엘',
    pt: 'Israel',
    it: 'Israele',
    ru: 'Израиль',
    zh: '以色列',
    'zh-TW': '以色列',
    'zh-HK': '以色列'
  },
  'Portugal': {
    en: 'Portugal',
    es: 'Portugal',
    fr: 'Portugal',
    de: 'Portugal',
    ja: 'ポルトガル',
    ko: '포르투갈',
    pt: 'Portugal',
    it: 'Portogallo',
    ru: 'Португалия',
    zh: '葡萄牙',
    'zh-TW': '葡萄牙',
    'zh-HK': '葡萄牙'  
  },
  'United Arab Emirates': {
    en: 'United Arab Emirates',
    es: 'Emiratos Árabes Unidos',
    fr: 'Émirats arabes unis',
    de: 'Vereinigte Arabische Emirate',
    ja: 'アラブ首長国連邦',
    ko: '아랍에미리트',
    pt: 'Emirados Árabes Unidos',
    it: 'Emirati Arabi Uniti',
    ru: 'Объединенные Арабские Эмираты',
    zh: '阿拉伯联合酋长国',
    'zh-TW': '阿拉伯聯合大公國',
    'zh-HK': '阿拉伯联合酋长国'
  },
  'Hong Kong': {
    en: 'Hong Kong',
    es: 'Hong Kong',
    fr: 'Hong Kong',
    de: 'Hongkong',
    ja: '香港',
    ko: '홍콩',
    pt: 'Hong Kong',
    it: 'Hong Kong',
    ru: 'Гонконг',
    zh: '香港',
    'zh-TW': '香港',
    'zh-HK': '香港'
  },
  'Colombia': {
    en: 'Colombia',
    es: 'Colombia',
    fr: 'Colombie',
    de: 'Kolumbien',
    ja: 'コロンビア',
    ko: '콜롬비아',
    pt: 'Colômbia',
    it: 'Colombia',
    ru: 'Колумбия',
    zh: '哥伦比亚',
    'zh-TW': '哥倫比亞',
    'zh-HK': '哥伦比亚'
  },
  'Denmark': {
    en: 'Denmark',
    es: 'Dinamarca',
    fr: 'Danemark',
    de: 'Dänemark',
    ja: 'デンマーク',
    ko: '덴마크',
    pt: 'Dinamarca',
    it: 'Danimarca',
    ru: 'Дания',
    zh: '丹麦',
    'zh-TW': '丹麥',
    'zh-HK': '丹麦'
  },
  'Finland': {
    en: 'Finland',
    es: 'Finlandia',
    fr: 'Finlande',
    de: 'Finnland',
    ja: 'フィンランド',
    ko: '핀란드',
    pt: 'Finlândia',
    it: 'Finlandia',
    ru: 'Финляндия',
    zh: '芬兰',
    'zh-TW': '芬蘭',
    'zh-HK': '芬兰'
  },
  'Ireland': {
    en: 'Ireland',
    es: 'Irlanda',
    fr: 'Irlande',
    de: 'Irland',
    ja: 'アイルランド',
    ko: '아일랜드',
    pt: 'Irlanda',
    it: 'Irlanda',
    ru: 'Ирландия',
    zh: '爱尔兰',
    'zh-TW': '愛爾蘭',
    'zh-HK': '爱尔兰'  
  },
  'Austria': {
    en: 'Austria',
    es: 'Austria',
    fr: 'Autriche',
    de: 'Österreich',
    ja: 'オーストリア',
    ko: '오스트리아',
    pt: 'Áustria',
    it: 'Austria',
    ru: 'Австрия',
    zh: '奥地利',
    'zh-TW': '奧地利',
    'zh-HK': '奥地利'
  },
  'Taiwan': {
    en: 'Taiwan',
    es: 'Taiwán',
    fr: 'Taïwan',
    de: 'Taiwan',
    ja: '台湾',
    ko: '대만',
    pt: 'Taiwan',
    it: 'Taiwan',
    ru: 'Тайвань',
    zh: '台湾',
    'zh-TW': '臺灣',
    'zh-HK': '台灣'
  },
  'Asia': {
    en: 'Asia',
    es: 'Asia',
    fr: 'Asie',
    de: 'Asien',
    ja: 'アジア',
    ko: '아시아',
    pt: 'Ásia',
    it: 'Asia',
    ru: 'Азия',
    zh: '亚洲',
    'zh-TW': '亞洲',
    'zh-HK': '亞洲'
  },
  'Americas': {
    en: 'Americas',
    es: 'Américas',
    fr: 'Amériques',
    de: 'Amerika',
    ja: 'アメリカ大陸',
    ko: '아메리카 대륙',
    pt: 'Américas',
    it: 'Americhe',
    ru: 'Америка',
    zh: '美洲',
    'zh-TW': '美洲',
    'zh-HK': '美洲'
  },
  'Africa': {
    en: 'Africa',
    es: 'África',
    fr: 'Afrique',
    de: 'Afrika',
    ja: 'アフリカ',
    ko: '아프리카',
    pt: 'África',
    it: 'Africa',
    ru: 'Африка',
    zh: '非洲',
    'zh-TW': '非洲',
    'zh-HK': '非洲'
  },
  'Middle East': {
    en: 'Middle East',
    es: 'Medio Oriente',
    fr: 'Moyen-Orient',
    de: 'Naher Osten',
    ja: '中東',
    ko: '중동',
    pt: 'Médio Oriente',
    it: 'Medio Oriente',
    ru: 'Ближний Восток',
    zh: '中东',
    'zh-TW': '中東',
    'zh-HK': '中東'
  },
  'China News': {
    en: 'China',
    es: 'China',
    fr: 'Chine',
    de: 'China',
    ja: '中国',
    ko: '중국',
    pt: 'China',
    it: 'Cina',
    ru: 'Китай',
    'zh-TW': '中國',
    'zh-HK': '中國',
    zh: '中国'
  },
  'Companies': {
    en: 'Companies',
    es: 'Empresas',
    fr: 'Entreprises',
    de: 'Unternehmen',
    ja: '企業',
    ko: '회사',
    pt: 'Empresas',
    it: 'Aziende',
    ru: 'Компании',
    'zh-TW': '公司',
    'zh-HK': '公司',
    zh: '公司'
  },
  'Markets': {
    en: 'Markets',
    es: 'Mercados',
    fr: 'Marchés',
    de: 'Märkte',
    ja: '市場',
    ko: '시장',
    pt: 'Mercados',
    it: 'Mercati',
    ru: 'Рынки',
    'zh-TW': '市場',
    'zh-HK': '市場',
    zh: '市场'
  },
  'Economy': {
    en: 'Economy',
    es: 'Economía',
    fr: 'Économie',
    de: 'Wirtschaft',
    ja: '経済',
    ko: '경제',
    pt: 'Economia',
    it: 'Economia',
    ru: 'Экономика',
    'zh-TW': '經濟',
    'zh-HK': '經濟',
    zh: '经济'
  },
  'Feature': {
    en: 'Feature',
    es: 'Reportaje',
    fr: 'Reportage',
    de: 'Reportage',
    ja: '特集',
    ko: '특집',
    pt: 'Reportagem',
    it: 'Servizio',
    ru: 'Репортаж',
    'zh-TW': '特寫',
    'zh-HK': '特寫',
    zh: '特写'
  },
  'Obituary': {
    en: 'Obituary',
    es: 'Obituario',
    fr: 'Nécrologie',
    de: 'Nachruf',
    ja: '訃報',
    ko: '부고',
    pt: 'Obituário',
    it: 'Necrologio',
    ru: 'Некролог',
    'zh-TW': '訃聞',
    'zh-HK': '訃聞',
    zh: '讣告'
  },
  'Opinion': {
    en: 'Opinion',
    es: 'Opinión',
    fr: 'Opinion',
    de: 'Meinung',
    ja: '意見',
    ko: '의견',
    pt: 'Opinião',
    it: 'Opinione',
    ru: 'Мнение',
    'zh-TW': '觀點',
    'zh-HK': '觀點',
    zh: '观点'
  },
  'News': {
    en: 'News',
    es: 'Noticias',
    fr: 'Nouvelles',
    de: 'Nachrichten',
    ja: 'ニュース',
    ko: '뉴스',
    pt: 'Notícias',
    it: 'Notizie',
    ru: 'Новости',
    'zh-TW': '新聞',
    'zh-HK': '新聞',
    zh: '新闻'
  },
  'Explainer': {
    en: 'Explainer',
    zh: '解读',
    es: 'Explicativo',
    fr: 'Explicatif',
    de: 'Erklärung',
    ja: '解説',
    ko: '설명자',
    pt: 'Explicativo',
    it: 'Spiegazione',
    ru: 'Пояснение',
    'zh-TW': '解讀',
    'zh-HK': '解讀'
  },
  'PODCASTS': {
    en: 'Podcasts',
    es: 'Podcasts',
    fr: 'Podcasts',
    de: 'Podcasts',
    ja: 'ポッドキャスト',
    ko: '팟캐스트',
    pt: 'Podcasts',
    it: 'Podcast',
    ru: 'Подкасты',
    'zh-TW': '播客',
    'zh-HK': '播客',
    zh: '播客'
  },
  'VIDEOS': {
    en: 'Videos',
    es: 'Videos',
    fr: 'Vidéos',
    de: 'Videos',
    ja: 'ビデオ',
    ko: '동영상',
    pt: 'Vídeos',
    it: 'Video',
    ru: 'Видео',
    'zh-TW': '視頻',
    'zh-HK': '視頻',
    zh: '视频'
  },
  'Life & Arts': {
    en: 'Life & Arts',
    es: 'Estilo de vida y arte',
    fr: 'Art de vivre',
    de: 'Leben & Kunst',
    ja: 'ライフ＆アート',
    ko: '라이프 & 아트',
    pt: 'Estilo de vida e arte',
    it: 'Vita e arte',
    ru: 'Жизнь и искусство',
    'zh-TW': '生活與藝術',
    'zh-HK': '生活與藝術',
    zh: '生活与艺术'
  },
  'Work & Careers': {
    en: 'Work & Careers',
    es: 'Trabajo y carreras',
    fr: 'Travail et carrières',
    de: 'Arbeit & Karriere',
    ja: '仕事とキャリア',
    ko: '직업 및 경력',
    pt: 'Trabalho e carreiras',
    it: 'Lavoro e carriere',
    ru: 'Работа и карьера',
    'zh-TW': '工作與職涯',
    'zh-HK': '工作與職涯',
    zh: '工作与职业'
  },
  'AI News': {
    en: 'AI',
    es: 'IA',
    fr: 'IA',
    de: 'AI',
    ja: 'AI',
    ko: 'AI',
    pt: 'IA',
    it: 'IA',
    'zh-TW': '人工智慧',
    'zh-HK': 'AI',
    zh: '人工智能',
    ru: 'ИИ'
  },
  Science: {
    en: 'Science',
    es: 'Ciencia',
    fr: 'Science',
    de: 'Wissenschaft',
    ja: '科学',
    ko: '과학',
    pt: 'Ciência',
    it: 'Scienza',
    'zh-TW': '科學',
    'zh-HK': '科學',
    zh: '科学',
    ru: 'Наука'
  },
  'US Presidential Election': {
    en: 'US Presidential Election',
    es: 'Elecciones presidenciales de EE. UU.',
    fr: 'Élection présidentielle américaine',
    de: 'US-Präsidentschaftswahl',
    ja: 'アメリカ大統領選挙',
    ko: '미국 대통령 선거',
    pt: 'Eleição presidencial dos EUA',
    it: 'Elezioni presidenziali statunitensi',
    ru: 'Президентские выборы в США',
    'zh-TW': '美國大選',
    'zh-HK': '美國大選',
    zh: '美国大选'
  },
  'Israel-Hamas War': {
    en: 'Israel-Hamas War',
    es: 'Guerra Israel-Hamas',
    fr: 'Guerre Israël-Hamas',
    de: 'Israel-Hamas-Krieg',
    ja: 'イスラエル・ハマス戦争',
    ko: '이스라엘-하마스 전쟁',
    pt: 'Guerra Israel-Hamas',
    it: 'Guerra tra Israele e Hamas',
    ru: 'Война Израиль-Хамас',
    'zh-TW': '以色列-哈馬斯戰爭',
    'zh-HK': '以色列-哈馬斯戰爭',
    zh: '以色列-哈马斯战争'
  },
  'Property': {
    en: 'Property',
    es: 'Propiedad',
    fr: 'Propriété',
    de: 'Immobilien',
    ja: '不動産',
    ko: '부동산',
    pt: 'Propriedade',
    it: 'Proprietà',
    ru: 'Недвижимость',
    'zh-TW': '房地產',
    'zh-HK': '房地產',
    zh: '房地产'
  },
  'Climate Change': {
    en: 'Climate Change',
    es: 'Cambio climático',
    fr: 'Changement climatique',
    de: 'Klimawandel',
    ja: '気候変動',
    ko: '기후 변화',
    pt: 'Mudança climática',
    it: 'Cambiamento climatico',
    ru: 'Климатические изменения',
    'zh-TW': '氣候變遷',
    'zh-HK': '氣候變遷',
    zh: '气候变化'
  },
  'Federal Reserve': {
    en: 'Federal Reserve',
    es: 'Reserva Federal',
    fr: 'Réserve fédérale',
    de: 'Federal Reserve',
    ja: '連邦準備銀行',
    ko: '연방준비제도',
    pt: 'Reserva Federal',
    it: 'Riserva Federale',
    ru: 'Федеральный резерв',
    'zh-TW': '美聯準',
    'zh-HK': '美聯儲',
    zh: '美联储'
  },
  'Chinese Economy': {
    en: 'Chinese Economy',
    es: 'Economía china',
    fr: 'Économie chinoise',
    de: 'Chinesische Wirtschaft',
    ja: '中国経済',
    ko: '중국 경제',
    pt: 'Economia chinesa',
    it: 'Economia cinese',
    ru: 'Китайская экономика',
    'zh-TW': '中國經濟',
    'zh-HK': '中國經濟',
    zh: '中国经济'
  },
  'Semiconductors': {
    en: 'Semiconductors',
    es: 'Semiconductores',
    fr: 'Semi-conducteurs',
    de: 'Halbleiter',
    ja: '半導体',
    ko: '반도체',
    pt: 'Semicondutores',
    it: 'Semiconduttori',
    ru: 'Полупроводники',
    'zh-TW': '半導體',
    'zh-HK': '半導體',
    zh: '半导体'
  },
  'Cryptocurrencies': {
    en: 'Cryptocurrencies',
    es: 'Criptomonedas',
    fr: 'Cryptomonnaies',
    de: 'Kryptowährungen',
    ja: '暗号通貨',
    ko: '암호화폐',
    pt: 'Criptomoedas',
    it: 'Criptovalute',
    ru: 'Криптовалюты',
    'zh-TW': '加密貨幣',
    'zh-HK': '加密貨幣',
    zh: '加密货币'
  },
  'Follow': {
    zh: '关注',
    en: 'Follow',
    es: 'Seguir',
    fr: 'Suivre',
    de: 'Folgen',
    ja: 'フォロー',
    ko: '팔로우',
    pt: 'Seguir',
    it: 'Segui',
    'zh-TW': '關注',
    'zh-HK': '關注',
    ru: 'Подписаться'
  }, 
  'Unfollow': {
    zh: '取消关注',
    en: 'Unfollow',
    es: 'Dejar de seguir',
    fr: 'Ne plus suivre',
    de: 'Entfolgen',
    ja: 'フォロー解除',
    ko: '언팔로우',
    pt: 'Deixar de seguir',
    it: 'Non seguire più',
    'zh-TW': '取消關注',
    'zh-HK': '取消關注',
    ru: 'Отписаться'
  },
  'Followed': {
    zh: '已关注',
    en: 'Followed',
    es: 'Seguido',
    fr: 'Suivi',
    de: 'Gefolgt',
    ja: 'フォロー済み',
    ko: '팔로우됨',
    pt: 'Seguido',
    it: 'Seguito',
    'zh-TW': '已關注',
    'zh-HK': '已關注',
    ru: 'Подписан'
  },
  'Follow the topics in this article': {
    en: 'Follow the topics in this article',
    zh: '相关话题',
    es: 'Sigue los temas en este artículo',
    fr: 'Suivez les sujets de cet article',
    de: 'Folgen Sie den Themen in diesem Artikel',
    ja: 'この記事のトピックをフォローする',
    ko: '이 기사의 주제를 팔로우하세요',
    pt: 'Siga os tópicos deste artigo',
    it: 'Segui gli argomenti di questo articolo',
    'zh-TW': '相關話題',
    'zh-HK': '相關話題',
    ru: 'Подписаться на темы в этой статье'
  },
  'Topics mentioned in this article': {
    en: 'Topics mentioned in this article',
    zh: '本文提及的话题',
    es: 'Temas mencionados en este artículo',
    fr: 'Sujets mentionnés dans cet article',
    de: 'In diesem Artikel erwähnte Themen',
    ja: 'この記事で言及されているトピック',
    ko: '이 기사에서 언급된 주제들',
    pt: 'Tópicos mencionados neste artigo',
    it: 'Argomenti menzionati in questo articolo',
    'zh-TW': '本文提及的話題',
    'zh-HK': '本文提及的話題',
    ru: 'Темы, упомянутые в этой статье'
  },
  Topics: {
    "zh": "话题",
    "en": "Topics",
    "es": "Temas",
    "fr": "Sujets",
    "de": "Themen",
    "ja": "トピック",
    "ko": "주제",
    "pt": "Tópicos",
    "it": "Argomenti",
    "zh-TW": "話題",
    "zh-HK": "話題",
    "ru": "Темы"
  },
  Topic: {
    "zh": "话题",
    "en": "Topic",
    "es": "Tema",
    "fr": "Sujet",
    "de": "Thema",
    "ja": "トピック",
    "ko": "주제",
    "pt": "Tópico",
    "it": "Argomento",
    "zh-TW": "話題",
    "zh-HK": "話題",
    "ru": "Тема"
  },
  'Input Interest': {
    "zh": "请输入您关注的话题",
    "en": "Please enter your topic of interest",
    "es": "Por favor, introduzca el tema de su interés",
    "fr": "Veuillez saisir le sujet qui vous intéresse",
    "de": "Bitte geben Sie Ihr Interessenthema ein",
    "ja": "興味のあるトピックを入力してください",
    "ko": "관심 있는 주제를 입력하세요",
    "pt": "Por favor, insira o tópico de seu interesse",
    "it": "Inserisci l'argomento di tuo interesse",
    "zh-TW": "請輸入您關注的話題",
    "zh-HK": "請輸入您關注的話題",
    "ru": "Пожалуйста, введите интересующую вас тему"
  },
  'Topic already followed': {
    "zh": "这个话题您已经关注了",
    "en": "You have already followed this topic",
    "es": "Ya has seguido este tema",
    "fr": "Vous avez déjà suivi ce sujet",
    "de": "Sie haben dieses Thema bereits verfolgt",
    "ja": "このトピックはすでにフォローしています",
    "ko": "이미 이 주제를 팔로우했습니다",
    "pt": "Você já seguiu este tópico",
    "it": "Hai già seguito questo argomento",
    "zh-TW": "您已經關注了這個話題",
    "zh-HK": "您已經關注了這個話題",
    "ru": "Вы уже следите за этой темой"
  },
  'PromptAdd': {
    zh: '您还没有关注任何话题，请点击这里添加',
    en: 'You have not followed any topics yet, please click here to add',
    es: 'Aún no has seguido ningún tema, haz clic aquí para añadir',
    fr: "Vous n'avez pas encore suivi de sujets, veuillez cliquer ici pour en ajouter",
    de: 'Sie haben noch keine Themen abonniert, klicken Sie hier um welche hinzuzufügen',
    ja: 'あなたはまだトピックをフォローしていません。追加するにはここをクリックしてください。',
    ko: '아직 팔로우한 주제가 없습니다. 여기를 클릭하여 추가하세요.', 
    pt: 'Você ainda não segue nenhum tópico, clique aqui para adicionar',
    it: 'Non hai ancora seguito alcun argomento, fai clic qui per aggiungerne',
    'zh-TW': '您還沒有關注任何主題，請點擊這裡添加',
    'zh-HK': '您仲未關注任何話題，請點擊呢度添加',
    ru: 'Вы пока не подписаны ни на одну тему, нажмите здесь, чтобы добавить'
  },
  'Artificial intelligence': {
    en: 'Artificial intelligence',
    es: 'Inteligencia artificial',
    fr: 'Intelligence artificielle',
    de: 'Künstliche Intelligenz',
    ja: '人工知能',
    ko: '인공 지능',
    pt: 'Inteligência artificial',
    it: 'Intelligenza artificiale',
    'zh-TW': '人工智慧',
    'zh-HK': '人工智能',
    zh: '人工智能',
    ru: 'Искусственный интеллект'
  },
  'Electric vehicles': {
    en: 'Electric vehicles',
    es: 'Vehículos eléctricos',
    fr: 'Véhicules électriques',
    de: 'Elektrofahrzeuge',
    ja: '電気自動車',
    ko: '전기 자동차',
    pt: 'Veículos elétricos',
    it: 'Veicoli elettrici',
    'zh-TW': '電動汽車',
    'zh-HK': '電動汽車',
    zh: '电动汽车',
    ru: 'Электромобили'
  },
  'Search': {
    en: 'Search',
    es: 'Buscar',
    fr: 'Chercher',
    de: 'Suchen',
    ja: '検索',
    ko: '검색',
    pt: 'Pesquisar',
    it: 'Cerca',
    'zh-TW': '搜索',
    'zh-HK': '搜尋',
    zh: '搜索',
    ru: 'Искать'
  },
  'Deep Dive': {
    zh: '深度报道',
    en: 'In-depth reports',
    es: 'Reportajes en profundidad',
    fr: 'Reportages approfondis',
    de: 'Vertiefende Berichte',
    ja: '綿密な報道',
    ko: '심층 보도',
    pt: 'Reportagens em profundidade',
    it: 'Approfondimenti',
    'zh-TW': '深度報導',
    'zh-HK': '深度報導',
    ru: 'Глубокие репортажи'
  },
  'Tech News': {
    zh: '科技',
    en: 'Technology',
    es: 'Tecnología',
    fr: 'Technologie',
    de: 'Technologie',
    ja: 'テクノロジー',
    ko: '기술',
    pt: 'Tecnologia',
    it: 'Tecnologia',
    'zh-TW': '科技',
    'zh-HK': '科技',
    ru: 'Технологии'
  },
  'Technology Sector': {
    zh: '科技',
    en: 'Technology',
    es: 'Tecnología',
    fr: 'Technologie',
    de: 'Technologie',
    ja: 'テクノロジー',
    ko: '기술',
    pt: 'Tecnologia',
    it: 'Tecnologia',
    'zh-TW': '科技',
    'zh-HK': '科技',
    ru: 'Технологии'
  },
  'Offer Help': {
    zh: '好的，需要我怎么帮助您？',
    en: 'Sure, how can I help you?',
    es: 'Claro, ¿en qué puedo ayudarle?',
    fr: 'Bien sûr, comment puis-je vous aider?',
    de: 'Ja, wie kann ich Ihnen helfen?',
    ja: '承知しました。何かお力になれることはありますか？',
    ko: '네, 무엇을 도와드릴까요?',
    pt: 'Claro, como posso ajudá-lo?',
    it: 'Certamente, in che modo posso aiutarti?',
    'zh-TW': '好的，有什麼我能幫到您的嗎？',
    'zh-HK': '好的，有什麼我能幫到您的嗎？',
    ru: 'Конечно, в чем я могу вам помочь?'
  },
  'Discuss Article': {
    zh: '关于这篇文章，如果您有任何问题，可以现在问我。',
    en: "If you have any questions about this article, feel free to ask me now.",
    es: "Si tienes alguna pregunta sobre este artículo, no dudes en preguntarme ahora.",
    fr: "Si vous avez des questions sur cet article, n'hésitez pas à me demander maintenant.",
    de: "Wenn Sie Fragen zu diesem Artikel haben, fragen Sie mich gerne jetzt.",
    ja: "この記事についての質問があれば、遠慮なくお聞きください。",
    ko: "이 기사에 대해 궁금한 점이 있으면 지금 저에게 물어보세요.",
    pt: "Se você tiver alguma dúvida sobre este artigo, sinta-se à vontade para me perguntar agora.",
    it: "Se hai domande su questo articolo, sentiti libero di chiedermi ora.",
    'zh-TW': "關於這篇文章，如果您有任何問題，可以現在問我。",
    'zh-HK': "關於呢篇文章，如果你有咩問題，可以即刻問我。",
    ru: "Если у вас есть вопросы по этой статье, не стесняйтесь спрашивать меня сейчас."
  },
  Finding: {
    zh: '好的，我来帮您查询...',
    en: 'Okay, let me help you search...',
    es: 'De acuerdo, déjame ayudarte a buscar...',
    fr: `D'accord, laissez-moi vous aider à chercher...`,
    de: 'Okay, ich helfe Ihnen gerne bei der Suche...',
    ja: '了解しました、検索をお手伝いします...',
    ko: '알겠습니다. 검색을 도와드리겠습니다...',
    pt: 'Certo, deixe-me ajudá-lo a pesquisar...',
    it: 'Va bene, lascia che ti aiuti a cercare...',
    'zh-TW': '好的，我來幫您查詢...',
    'zh-HK': '好的，我來幫您查詢...',
    ru: 'Хорошо, я помогу вам найти...'
  },
  FindingMyFT: {
    zh: '为您展示FT最新的内容，您也可以<a>点击这里设置您关注的话题和阅读偏好</a>',
    en: 'Let me show you the latest content from FT, you can also <a>click here to set the topics you are interested in and your reading preferences</a>',
    es: 'Déjame mostrarte el contenido más reciente de FT, también puedes <a>hacer clic aquí para configurar los temas que sigues y tus preferencias de lectura</a>',
    fr: 'Laissez-moi vous montrer le contenu le plus récent de FT, vous pouvez également <a>cliquer ici pour définir les sujets que vous suivez et vos préférences de lecture</a>',
    de: 'Lassen Sie mich Ihnen die neuesten Inhalte von FT zeigen, Sie können auch <a>hier klicken, um die Themen, denen Sie folgen, und Ihre Leseprioritäten festzulegen</a>',
    ja: 'FTの最新コンテンツをご覧いただけます。また、<a>こちらをクリックして、フォローするトピックと読書の嗜好を設定することもできます</a>',
    ko: 'FT의 최신 컨텐츠를 보여드리겠습니다. 또한 <a>여기를 클릭하여 관심 있는 주제와 독서 선호도를 설정할 수 있습니다</a>',
    pt: 'Deixe-me mostrar os conteúdos mais recentes da FT, você também pode <a>clicar aqui para definir os tópicos que segue e suas preferências de leitura</a>',
    it: 'Lascia che ti mostri i contenuti più recenti di FT, puoi anche <a>fare clic qui per impostare gli argomenti che segui e le tue preferenze di lettura</a>',
    'zh-TW': '讓我展示FT最新的內容，您也可以<a>點擊這裡設定您關注的話題和閱讀偏好</a>',
    'zh-HK': '讓我展示FT最新的內容，您也可以<a>點擊這裡設定您關注的話題和閱讀偏好</a>',
    ru: 'Давайте я покажу вам самые свежие материалы FT, вы также можете <a>нажать здесь, чтобы настроить темы, которые вы отслеживаете, и ваши предпочтения в чтении</a>'
  },
  FindingMostPopular: {
    zh: '好的，我来帮您查询FT的热门文章...',
    en: 'Okay, let me help you check the most popular content on the FT...',
    es: 'De acuerdo, déjame ayudarte a buscar el contenido más popular en FT...',
    fr: 'D\'accord, laissez-moi vous aider à chercher le contenu le plus populaire sur FT...',
    de: 'Okay, ich helfe Ihnen, die beliebtesten Inhalte auf FT zu finden...',
    ja: '了解しました、FTの人気コンテンツを検索のお手伝いをします...',
    ko: '알겠습니다, FT에서 가장 인기있는 콘텐츠를 검색하는 것을 도와드리겠습니다...',
    pt: 'Certo, deixe-me ajudá-lo a pesquisar o conteúdo mais popular no FT...',
    it: 'Va bene, lascia che ti aiuti a cercare il contenuto più popolare su FT...',
    'zh-TW': '好的，我來幫您查詢FT的熱門文章...',
    'zh-HK': '好的，我來幫您查詢FT的熱門文章...',
    ru: 'Хорошо, я помогу вам найти самый популярный контент на FT...'
  },
  ApplyAndStartOver: {
    zh: '应用并重启',
    en: 'Apply and Restart',
    es: 'Aplicar y Reiniciar',
    fr: 'Appliquer et Redémarrer',
    de: 'Anwenden und Neustarten',
    ja: '適用して再起動',
    ko: '적용하고 재시작',
    pt: 'Aplicar e Reiniciar',
    it: 'Applica e Riavvia',
    'zh-TW': '應用並重啟',
    'zh-HK': '應用並重啟',
    ru: 'Применить и Перезагрузить'
  },
  Read: {
    "zh": "已读",
    "en": "Read",
    "es": "Leído",
    "fr": "Lu",
    "de": "Gelesen",
    "ja": "読了",
    "ko": "읽음",
    "pt": "Lido",
    "it": "Letto",
    "zh-TW": "已讀",
    "zh-HK": "已讀",
    "ru": "Прочитано"
  },
  "Read Articles": {
    "zh": "已读文章",
    "en": "Read Articles",
    "es": "Artículos Leídos",
    "fr": "Articles Lus",
    "de": "Gelesene Artikel",
    "ja": "読了した記事",
    "ko": "읽은 기사",
    "pt": "Artigos Lidos",
    "it": "Articoli Letti",
    "zh-TW": "已讀文章",
    "zh-HK": "已讀文章",
    "ru": "Прочитанные Статьи"
  },
  "Show": {
    "zh": "显示",
    "en": "Show",
    "es": "Mostrar",
    "fr": "Afficher",
    "de": "Anzeigen",
    "ja": "表示",
    "ko": "보이기",
    "pt": "Mostrar",
    "it": "Mostra",
    "zh-TW": "顯示",
    "zh-HK": "顯示",
    "ru": "Показать"
  },
  "Collapse to Bottom": {
    "zh": "折叠到底部",
    "en": "Collapse to Bottom",
    "es": "Colapsar al Final",
    "fr": "Réduire en Bas",
    "de": "Nach Unten Einklappen",
    "ja": "下部に折りたたむ",
    "ko": "아래로 접기",
    "pt": "Colapsar para o Fundo",
    "it": "Collassare in Basso",
    "zh-TW": "摺疊到底部",
    "zh-HK": "摺疊到底部",
    "ru": "Свернуть вниз"
  },
  ReadingPreferences: {
    "zh": "阅读偏好",
    "en": "Reading Preferences",
    "es": "Preferencias de Lectura",
    "fr": "Préférences de Lecture",
    "de": "Lesepräferenzen",
    "ja": "読書の好み",
    "ko": "독서 선호도",
    "pt": "Preferências de Leitura",
    "it": "Preferenze di Lettura",
    "zh-TW": "閱讀偏好",
    "zh-HK": "閱讀偏好",
    "ru": "Предпочтения в Чтении"
  },
  PrepareingQuiz: {
    zh: '为您准备小测...',
    en: 'Preparing a quiz for you...',
    es: 'Preparando un cuestionario para ti...',
    fr: `Préparation d'un quiz pour vous...`,
    de: 'Bereite einen Quiz für dich vor...',
    ja: 'あなたのためにクイズを準備しています...',
    ko: '퀴즈를 준비 중입니다...',
    pt: 'Preparando um questionário para você...',
    it: 'Preparando un quiz per te...',
    'zh-TW': '為您準備小測...',
    'zh-HK': '為您準備小測...',
    ru: 'Подготовка викторины для вас...'
  },
  'What do you want to find?': {
    zh: '好的，您可以点击下面这些最为常见的查询，也可以告诉我您想找什么内容。',
    en: 'Okay, you can click on the most common queries below, or tell me what content you are looking for.',
    es: 'De acuerdo, puedes hacer clic en las consultas más comunes a continuación, o decirme qué contenido estás buscando.',
    fr: `D'accord, vous pouvez cliquer sur les requêtes les plus courantes ci-dessous, ou me dire quel contenu vous recherchez.`,
    de: 'Okay, Sie können auf die häufigsten Abfragen unten klicken oder mir sagen, wonach Sie suchen.',
    ja: 'わかりました。以下の最も一般的なクエリをクリックするか、お探しのコンテンツを教えてください。',
    ko: '알겠습니다. 가장 일반적인 쿼리를 아래에서 클릭하거나 찾으시는 콘텐츠를 말씀해주세요.',
    pt: 'Ok, você pode clicar nas consultas mais comuns abaixo ou me dizer que conteúdo está procurando.',
    it: 'Va bene, puoi cliccare sulle query più comuni qui sotto o dirmi quale contenuto stai cercando.',
    'zh-TW': '好的，您可以點擊下面這些最常見的查詢，或告訴我您要找什麼內容。',
    'zh-HK': '好嘢，您可以喺下面啲最常見嘅查詢入面揀一個，或者講俾我知您要搵咩嘢。',
    ru: 'Хорошо, вы можете нажать на наиболее распространенные запросы ниже или сообщить мне, какой контент вы ищете.'
  },
  'Find More': {
    zh: '您可以点击下面这些最为常见的查询，或者告诉我您想找什么内容。',
    en: 'You can click on these most common queries below, or tell me what content you are looking for.',
    es: 'Puede hacer clic en estas consultas más comunes a continuación, o decirme qué contenido está buscando.',
    fr: 'Vous pouvez cliquer sur ces requêtes les plus courantes ci-dessous, ou me dire quel contenu vous recherchez.',
    de: 'Sie können auf diese am häufigsten gestellten Abfragen unten klicken oder mir sagen, wonach Sie suchen.',
    ja: '以下の最も一般的なクエリをクリックするか、探しているコンテンツを教えてください。',
    ko: '가장 일반적인 쿼리 중 하나를 클릭하거나 찾으려는 콘텐츠를 알려주세요.',
    pt: 'Você pode clicar nas consultas mais comuns abaixo ou me dizer que conteúdo está procurando.',
    it: 'Puoi cliccare su queste query più comuni qui sotto, o dirmi quale contenuto stai cercando.',
    'zh-TW': '您可以點擊下面這些最常見的查詢，或告訴我您想要尋找什麼內容。',
    'zh-HK': '你可以按下面最常見的查詢，或者告訴我你想搵咩內容。',
    ru: 'Вы можете щелкнуть на эти самые распространенные запросы ниже или сообщить мне, какой контент вы ищете.'
  },
  'Discuss More': {
    zh: '如果有任何关于FT最新内容的问题，请立即问我。',
    en: 'If you have any questions about the latest FT content, please ask me immediately.',
    es: 'Si tiene alguna pregunta sobre el contenido más reciente de FT, pregúnteme de inmediato.',
    fr: 'Si vous avez des questions sur le contenu le plus récent de FT, demandez-moi immédiatement.',
    de: 'Wenn Sie Fragen zum neuesten FT-Inhalt haben, fragen Sie mich bitte sofort.',
    ja: '最新のFTコンテンツに関する質問がある場合は、すぐに私に尋ねてください。',
    ko: '최신 FT 콘텐츠에 대한 질문이 있으면 즉시 저에게 물어보세요.',
    pt: 'Se você tiver alguma dúvida sobre o conteúdo mais recente do FT, pergunte-me imediatamente.',
    it: 'Se hai domande sul contenuto più recente di FT, chiedimi immediatamente.',
    'zh-TW': '如果有關於FT最新內容的問題，請立即問我。',
    'zh-HK': '如果有關FT最新內容的問題，請立即問我。',
    ru: 'Если у вас есть вопросы о последних материалах FT, пожалуйста, спросите меня немедленно.'
  },
  'DoSomethingElse': {
    zh: '聊点别的',
    en: `Talk about something else`,
    es: 'Hablemos de algo más',
    fr: `Parlons d'autre chose`,
    de: 'Lass uns über etwas anderes sprechen',
    ja: '他の話題にしましょう',
    ko: '다른 얘기 좀 하자',
    pt: 'Vamos falar sobre outra coisa',
    it: `Parliamo d'altro`,
    'zh-TW': '聊點別的',
    'zh-HK': '傾下計啦',
    ru: 'Давайте поговорим о чем-то другом'
  },
  'Set Your Preferences': {
    zh: '您可以在这里修改您的偏好及设置',
    en: 'You can modify your preferences and settings here.',
    es: 'Puede modificar sus preferencias y configuraciones aquí.',
    fr: 'Vous pouvez modifier vos préférences et paramètres ici.',
    de: 'Sie können hier Ihre Einstellungen und Vorlieben ändern.',
    ja: 'ここで好みや設定を変更できます。',
    ko: '여기에서 선호도와 설정을 수정할 수 있습니다.',
    pt: 'Você pode modificar suas preferências e configurações aqui.',
    it: 'Puoi modificare le tue preferenze e impostazioni qui.',
    'zh-TW': '您可以在這裡修改您的偏好和設置。',
    'zh-HK': '您可以在這裡修改您的偏好和設置。',
    ru: 'Вы можете изменить свои предпочтения и настройки здесь.'
  },
  'Setting': {
    zh: '设置',
    en: 'Settings',
    es: 'Ajustes',
    fr: 'Paramètres',
    de: 'Einstellungen',
    ja: '設定',
    ko: '설정',
    pt: 'Configurações',
    it: 'Impostazioni',
    'zh-TW': '設定',
    'zh-HK': '設定',
    ru: 'Настройки'
  },
  'My Interests': {
    zh: '我的关注',
    en: 'My Interests',
    "es": "Mis Intereses",
    "fr": "Mes Intérêts",
    "de": "Meine Interessen",
    "ja": "私の興味",
    "ko": "내 관심사",
    "pt": "Meus Interesses",
    "it": "I Miei Interessi",
    "zh-TW": "我的興趣",
    "zh-HK": "我的興趣",
    "ru": "Мои Интересы"
  },
  'Add': {
    zh: '添加',
    en: 'Add', 
    es: 'Añadir',
    fr: 'Ajouter',
    de: 'Hinzufügen',
    ja: '追加',
    ko: '추가',
    pt: 'Adicionar',
    it: 'Aggiungi',
    'zh-TW': '新增',
    'zh-HK': '新增',
    ru: 'Добавить'
  },
  'Add Interests': {
    zh: '添加兴趣', 
    en: 'Add Interests',
    es: 'Añadir intereses',
    fr: 'Ajouter des intérêts', 
    de: 'Interessen hinzufügen',
    ja: '興味を追加',
    ko: '관심사 추가',
    pt: 'Adicionar interesses',
    it: 'Aggiungi interessi',
    'zh-TW': '新增興趣',
    'zh-HK': '新增興趣',
    ru: 'Добавить интересы'
  },
  'Popular': {
    zh: '热门',
    en: 'Popular', 
    es: 'Popular',
    fr: 'Populaire',
    de: 'Beliebt', 
    ja: '人気',
    ko: '인기',
    pt: 'Popular',
    it: 'Popolare',
    'zh-TW': '熱門',
    'zh-HK': '熱門',
    ru: 'Популярный'
  },
  'Language': {
    zh: '语言',
    en: 'Language',
    es: 'Idioma',
    fr: 'Langue',
    de: 'Sprache',
    ja: '言語',
    ko: '언어',
    pt: 'Língua',
    it: 'Lingua',
    'zh-TW': '語言',
    'zh-HK': '語言',
    ru: 'Язык'
  },
  'Font Size': {
    zh: '字体大小',
    en: 'Font Size',
    es: 'Tamaño de Fuente',
    fr: 'Taille de Police',
    de: 'Schriftgröße',
    ja: 'フォントサイズ',
    ko: '글꼴 크기',
    pt: 'Tamanho da Fonte',
    it: 'Dimensioni del Carattere',
    'zh-TW': '字型大小',
    'zh-HK': '字型大小',
    ru: 'Размер шрифта'
  },
  'Read Article': {
    zh: '阅读文章',
    en: 'Read Article',
    es: 'Leer artículo',
    fr: `Lire l'article`,
    de: 'Artikel lesen',
    ja: '記事を読む',
    ko: '기사 읽기',
    pt: 'Ler artigo',
    it: 'Leggi articolo',
    'zh-TW': '閱讀文章',
    'zh-HK': '閱讀文章',
    ru: 'Прочитать статью'
  },
  'Pop Out': {
    zh: '打开新页面',
    en: 'Pop Out',
    es: 'Abrir en nueva pestaña',
    fr: 'Ouvrir dans un nouvel onglet',
    de: 'In neuem Fenster öffnen',
    ja: '新しいウィンドウで開く',
    ko: '새 창에서 열기',
    pt: 'Abrir em nova janela',
    it: 'Apri in una nuova finestra',
    'zh-TW': '開新分頁',
    'zh-HK': '開新分頁',
    ru: 'Открыть в новом окне'
  },
  'In Chat': {
    zh: '在对话中',
    en: 'In Chat',
    es: 'En el chat',
    fr: 'Dans le chat',
    de: 'Im Chat',
    ja: 'チャット内',
    ko: '채팅에서',
    pt: 'No chat',
    it: 'In chat',
    'zh-TW': '在聊天中',
    'zh-HK': '在聊天中',
    ru: 'В чате'
  },
  'Please Select': {
    zh: '请选择',
    en: 'Please Select',
    es: 'Por favor, seleccione',
    fr: 'Veuillez sélectionner',
    de: 'Bitte auswählen',
    ja: '選択してください',
    ko: '선택하세요',
    pt: 'Por favor Selecione',
    it: 'Seleziona per favore',
    'zh-TW': '請選擇',
    'zh-HK': '請選擇',
    ru: 'Пожалуйста, выберите'
  },
  'Smallest': {
    zh: '最小',
    en: 'Smallest',
    es: 'Más Pequeño',
    fr: 'Le plus petit',
    de: 'Kleinsten',
    ja: '最小',
    ko: '가장 작은',
    pt: 'O menor',
    it: 'Il più piccolo',
    'zh-TW': '最小',
    'zh-HK': '最小',
    ru: 'Самый маленький'
  },
  'Smaller': {
    zh: '较小',
    en: 'Smaller',
    es: 'Menor',
    fr: 'Plus petit',
    de: 'Kleiner',
    ja: '小さい',
    ko: '작은',
    pt: 'Menor',
    it: 'Meno',
    'zh-TW': '較小',
    'zh-HK': '較小',
    ru: 'Меньше'
  },
  'Default': {
    zh: '默认',
    en: 'Default',
    es: 'Predeterminado',
    fr: 'Défaut',
    de: 'Standard',
    ja: 'デフォルト',
    ko: '기본값',
    pt: 'Padrão',
    it: 'Predefinito',
    'zh-TW': '預設',
    'zh-HK': '預設',
    ru: 'По умолчанию'
  },
  'Larger': {
    zh: '较大',
    en: 'Larger',
    es: 'Mayor',
    fr: 'Plus grand',
    de: 'Größer',
    ja: '大きい',
    ko: '더 큰',
    pt: 'Maior',
    it: 'Più grande',
    'zh-TW': '較大',
    'zh-HK': '較大',
    ru: 'Больше'
  },
  'Largest': {
    zh: '最大',
    en: 'Largest',
    es: 'Más Grande',
    fr: 'Le plus grand',
    de: 'Größten',
    ja: '最大',
    ko: '가장 큰',
    pt: 'O maior',
    it: 'Il più grande',
    'zh-TW': '最大',
    'zh-HK': '最大',
    ru: 'Самый большой'
  },
  'Sign In': {
    zh: '登录',
    en: 'Sign In',
    es: 'Iniciar sesión',
    fr: 'Se connecter',
    de: 'Anmelden',
    ja: 'ログイン',
    ko: '로그인',
    pt: 'Entrar',
    it: 'Accedi',
    'zh-TW': '登入',
    'zh-HK': '登入',
    ru: 'Вход'
  },
  'Sign Up': {
    zh: '注册',
    en: 'Sign Up',
    es: 'Registrarse',
    fr: 'S\'inscrire',
    de: 'Registrieren',
    ja: '新規登録',
    ko: '회원가입',
    pt: 'Registar-se',
    it: 'Registrati',
    'zh-TW': '註冊',
    'zh-HK': '註冊',
    ru: 'Регистрация'
  },
  'Sign Out': {
    zh: '退出',
    en: 'Sign Out',
    es: 'Cerrar sesión',
    fr: 'Se déconnecter',
    de: 'Abmelden',
    ja: 'ログアウト',
    ko: '로그아웃',
    pt: 'Sair',
    it: 'Esci',
    'zh-TW': '登出',
    'zh-HK': '登出',
    ru: 'Выход'
  },
  'Article Translation Preference': {
    zh: '文章翻译偏好',
    en: 'Article Translation Preference',
    es: 'Preferencia de Traducción de Artículo',
    fr: 'Préférence de Traduction d\'Article',
    de: 'Artikel Übersetzungsvorlieben',
    ja: '記事の翻訳の好み',
    ko: '기사 번역 선호',
    pt: 'Preferência de Tradução de Artigo',
    it: 'Preferenza di Traduzione dell\'Articolo',
    'zh-TW': '文章翻譯偏好',
    'zh-HK': '文章翻譯偏好',
    ru: 'Предпочтения Перевода Статьи'
  },
  'Both Human and Machine Translation': {
    zh: '机器翻译及人工翻译',
    en: 'Machine and Human Translation',
    es: 'Traducción Automática y Humana',
    fr: 'Traduction Automatique et Humaine',
    de: 'Maschinen- und Menschliche Übersetzung',
    ja: '機械翻訳および人間の翻訳',
    ko: '기계 번역 및 인간 번역',
    pt: 'Tradução por Máquina e Humana',
    it: 'Traduzione Automatica e Umana',
    'zh-TW': '機器翻譯及人工翻譯',
    'zh-HK': '機器翻譯及人工翻譯',
    ru: 'Машинный и Человеческий Перевод'
  },
  'Only Use Human Translation': {
    zh: '仅人工翻译',
    en: 'Only Use Human Translation',
    es: 'Usar Solo Traducción Humana',
    fr: 'Utiliser Uniquement la Traduction Humaine',
    de: 'Nur Menschliche Übersetzung Verwenden',
    ja: '人間の翻訳のみを使用',
    ko: '인간 번역만 사용',
    pt: 'Usar Apenas Tradução Humana',
    it: 'Usa Solo la Traduzione Umana',
    'zh-TW': '僅人工翻譯',
    'zh-HK': '僅人工翻譯',
    ru: 'Использовать Только Человеческий Перевод'
  },
  'Prompt Set Intention': {
    zh: '请先点击上面的按钮，选择您需要的服务',
    en: 'Please click the button above and select the service you need.',
    es: 'Por favor, haga clic en el botón de arriba y seleccione el servicio que necesita.',
    fr: 'Veuillez cliquer sur le bouton ci-dessus et sélectionner le service dont vous avez besoin.',
    de: 'Bitte klicken Sie auf die Schaltfläche oben und wählen Sie den gewünschten Service aus.',
    ja: '上のボタンをクリックして、必要なサービスを選択してください。',
    ko: '위의 버튼을 클릭하여 필요한 서비스를 선택하십시오.',
    pt: 'Por favor, clique no botão acima e selecione o serviço que você precisa.',
    it: 'Fare clic sul pulsante sopra e selezionare il servizio di cui avete bisogno.',
    'zh-TW': '請先點擊上面的按鈕，選擇您需要的服務',
    'zh-HK': '請先按上面的按鈕，選擇您需要的服務',
    ru: 'Пожалуйста, нажмите на кнопку выше и выберите нужный сервис.'
  },
  'Read_It_Later':{
    zh: '稍后再看',
    en: 'Read Later',
    es: 'Leer más tarde',
    fr: 'Lire plus tard',
    de: 'Für später merken',
    ja: '後で読む',
    ko: '나중에 읽기',
    pt: 'Ler depois',
    it: 'Leggi dopo',
    'zh-TW': '稍後再看',
    'zh-HK': '稍後再看',
    ru: 'Прочитать позже'
  },
  'Read_It_Later_Flag':{
    zh: '文章已在下方加载完毕。',
    en: 'Content has been loaded below.',
    es: 'El contenido se ha cargado a continuación.',
    fr: 'Le contenu a été chargé ci-dessous.',
    de: 'Der Inhalt wurde unten geladen.',
    ja: 'コンテンツは下に読み込まれました。',
    ko: '콘텐츠가 아래에로드되었습니다.',
    pt: 'O conteúdo foi carregado abaixo.',
    it: 'Il contenuto è stato caricato sotto.',
    'zh-TW': '內容已在下方加載。',
    'zh-HK': '內容已在下方加載。',
    ru: 'Контент загружен ниже.'
    },
    'jump-to-article':{
      zh: '跳转到文章',
      en: 'Jump to Article',
      es: 'Ir al Artículo',
      fr: 'Aller à l\'article',
      de: 'Zum Artikel springen',
      ja: '記事へ移動',
      ko: '기사로 이동',
      pt: 'Ir para o Artigo',
      it: 'Vai all\'Articolo',
      'zh-TW': '跳轉到文章',
      'zh-HK': '跳轉到文章',
      ru: 'Перейти к статье'
    },
    'Bilingual': {
      zh: '对照',
      en: 'Bilingual',
      es: 'Bilingüe',
      fr: 'Bilingue',
      
      de: 'Zweisprachig',
      ja: 'バイリンガル',
      ko: '이중 언어',
      pt: 'Bilíngue',
      it: 'Bilingue',
      'zh-TW': '雙語',
      'zh-HK': '雙語',
      ru: 'Двуязычный'
    },
    'ai-disclaimer-proofread': {
      zh: '为了第一时间为您呈现此信息，本文内容为AI翻译和校对，仅供参考',
      en: 'To present this information to you as soon as possible, the content of this article is AI translated and proofread, for reference only',
      es: 'Para presentar esta información lo antes posible, el contenido de este artículo está traducido y revisado por IA, solo para referencia',
      fr: `Pour présenter cette information le plus rapidement possible, le contenu de cet article est traduit et relu par l'IA, uniquement à titre de référence`,
      de: 'Um Ihnen diese Informationen so schnell wie möglich zu präsentieren, ist der Inhalt dieses Artikels von AI übersetzt und korrekturgelesen, nur zur Referenz',
      ja: 'この情報をできるだけ早く提供するため、この記事の内容はAIによる翻訳と校正であり、参考のみです',
      ko: '최대한 빠르게 이 정보를 제공하기 위해이 문서의 내용은 AI 번역 및 교정으로 작성되었습니다. 참조 용도로만 사용하십시오',
      pt: 'Para apresentar esta informação o mais rapidamente possível, o conteúdo deste artigo é traduzido e revisado por AI, apenas para referência',
      it: `Per presentare queste informazioni il prima possibile, il contenuto di questo articolo è tradotto e revisionato dall'IA, solo per riferimento`,
      'zh-TW': '為了第一時間為您呈現此信息，本文內容為AI翻譯和校對，僅供參考',
      'zh-HK': '為了第一時間為您呈現此信息，本文內容為AI翻譯和校對，僅供參考',
      ru: 'Чтобы представить вам эту информацию как можно скорее, содержание этой статьи переведено и проверено на ИИ, только для справки'
    },
    'ai-disclaimer': {
      zh: '为了第一时间为您呈现此信息，本文内容为机器翻译，仅供参考',
      en: 'To present this information to you as quickly as possible, this article has been machine translated and is for reference only',
      es: 'Para presentarle esta información lo más rápido posible, este artículo ha sido traducido por máquina y es solo para referencia',
      fr: 'Pour vous présenter ces informations le plus rapidement possible, cet article a été traduit par machine et est uniquement à titre de référence',
      de: 'Um Ihnen diese Informationen so schnell wie möglich zu präsentieren, wurde dieser Artikel maschinell übersetzt und dient nur als Referenz',
      ja: 'この情報をできるだけ早く提供するため、この記事は機械翻訳され、参考のみとして提供されています',
      ko: '이 정보를 가능한 빠르게 제공하기 위해 이 기사는 기계 번역되었으며 참조만을 위한 것입니다',
      pt: 'Para apresentar esta informação o mais rápido possível, este artigo foi traduzido por máquina e é apenas para referência',
      it: 'Per presentare queste informazioni il più rapidamente possibile, questo articolo è stato tradotto con una macchina ed è solo a scopo di riferimento',
      'zh-TW': '為了第一時間為您呈現此資訊，本文內容為機器翻譯，僅供參考',
      'zh-HK': '為了第一時間為您呈現此資訊，本文內容為機器翻譯，僅供參考',
      ru: 'Чтобы предоставить вам эту информацию как можно быстрее, этот текст был переведен с помощью машины и предназначен только для справки'
    }, 
    NewsQuiz: {
      zh: '新闻小测',
      en: 'News Quiz',
      es: 'Prueba de noticias',
      fr: `Quiz d'actualités`,
      de: 'Nachrichtenquiz',
      ja: 'ニュースクイズ',
      ko: '뉴스 퀴즈',
      pt: 'Quiz de notícias',
      it: 'Quiz di notizie',
      'zh-TW': '新聞小測',
      'zh-HK': '新聞小測',
      ru: 'Новостная викторина'
    }, 
    ChatDisclaimer: {
      "en": "Chat bots can make mistakes. Consider checking important information.",
      "zh": "聊天机器人可能会犯错误。请考虑核对重要信息。",
      "es": "Los chatbots pueden cometer errores. Considere verificar la información importante.",
      "fr": "Les chatbots peuvent faire des erreurs. Envisagez de vérifier les informations importantes.",
      "de": "Chatbots können Fehler machen. Überlegen Sie, wichtige Informationen zu überprüfen.",
      "ja": "チャットボットは間違いを犯すことがあります。重要な情報を確認することを検討してください。",
      "ko": "챗봇은 실수를 할 수 있습니다. 중요한 정보를 확인하는 것을 고려해보세요.",
      "pt": "Chatbots podem cometer erros. Considere verificar informações importantes.",
      "it": "I chatbot possono commettere errori. Considera di controllare le informazioni importanti.",
      "zh-TW": "聊天機器人可能會犯錯誤。請考慮核對重要資訊。",
      "zh-HK": "聊天機械人可能會犯錯。請考慮核對重要資訊。",
      "ru": "Чат-боты могут допускать ошибки. Рассмотрите возможность проверки важной информации."
    }      
};

// MARK: - Normalize the statusDict to make it case-insensitive for lookup
let statusDict = {};

for (const key of Object.keys(statusDictOriginal)) {
  const newKey = key.toLowerCase();
  statusDict[newKey] = statusDictOriginal[key];
}
statusDictOriginal = {};

/* jshint ignore:end */